
[#sec-source-code]
= Source code and literals

This section contains editorial rules on how to write down source code:

* <<#sec-ASM-43>>
* <<#sec-ASM-121>>
* <<#sec-ASM-88>>
* <<#sec-ASM-14>>
* <<#sec-ASM-79>>
* <<#sec-ASM-53>>


[#sec-ASM-14]
== Create an anchor with an UUID for a referenced code block (ASM-14)

The code block anchor consists of `[#`, the string `code-`, a following UUID, and `]`.

*Exceptions*

If you do not know how to use unique IDs, insert `[#tag-uid]` as a placeholder.
The placeholder will trigger a pipeline warning so that the technical writer can help with creating a unique ID.

*Example*

[.underline]#Code#

```
[#code-7a608cac-62b9-4992-8079-d382a55128b2]
[source, xml, linenums]
----
<OpenDRIVE xmlns="https://code.asam.net/simulation/standard/opendrive_schema/">
...
</OpenDRIVE>
----
```

[.underline]#Result#

[#code-7a608cac-62b9-4992-8079-d382a55128b2]
[source, xml, linenums]
----
<OpenDRIVE xmlns="https://code.asam.net/simulation/standard/opendrive_schema/">
...
</OpenDRIVE>
----


*Source*

* ASAM Writing Guide: Tags
* ASAM Writing Guide: 6.2. Source code fragments


[#sec-ASM-88]
== Use AsciiDoc syntax for source code snippets (ASM-88)

If you cannot or do not want to reference a source code file, you can add source code as a snippet to your AsciiDoc file.
In case of future changes, be aware that you have to maintain two places: your original source code and the snippet in the AsciiDoc file.

*Instructions*

To add source code snippets:

. Copy the part of source code you want to use as a snippet.
. Paste the snippet into your AsciiDoc file.
. Insert the following information:
    * an ID (refer to <<#sec-ASM-14>>)
    * a caption
    * additional information as comma-separated values with spaces
    * delimiters

The following additional information shall or may be used:

* Always use `source`.
* Add the source code language for syntax highlighting. For example, `osc2`, `xml`, or `java`.
* Always use `linenums`.

*Exceptions*

There are no exceptions.

*Example*

[.underline]#Code#

```
[#code-1e787b21-eb85-4582-9763-6c2319770928]
[source, xml, linenums]
----
<junction name="" id="1">
    <connection id="0" incomingRoad="2" connectingRoad="4" contactPoint="start">
        <laneLink from="-1" to="-1"/>
    </connection>
    <connection id="1" incomingRoad="3" connectingRoad="5" contactPoint="start">
        <laneLink from="-1" to="-1"/>
    </connection>
</junction>
----
```

[.underline]#Result#

[#code-1e787b21-eb85-4582-9763-6c2319770928]
[source, xml, linenums]
----
<junction name="" id="1">
    <connection id="0" incomingRoad="2" connectingRoad="4" contactPoint="start">
        <laneLink from="-1" to="-1"/>
    </connection>
    <connection id="1" incomingRoad="3" connectingRoad="5" contactPoint="start">
        <laneLink from="-1" to="-1"/>
    </connection>
</junction>
----

*Source*

* ASAM Writing Guide: 6.3. Source code snippets
* https://docs.asciidoctor.org/asciidoc/latest/verbatim/source-blocks/


[#sec-ASM-43]
== Use a single backtick before and after inline literals (ASM-43)

* Use a single grave accent U+0060, also called backtick, (`++`++`) before and after inline literals.
* Do not use pairs of double backticks (`++``++`).

In AsciiDoc, double backticks are used https://docs.asciidoctor.org/asciidoc/latest/text/monospace/#unconstrained[for text formatting in certain cases].
Unfortunately, this causes poor wording and readability and therefore shall not be used.

*Exceptions*

There are no exceptions.

*Example*

[.underline]#Code#

`+++`term`+++`

[.underline]#Result#

`term`

[#tab-ce27729f-33c4-47b2-a579-e7a1c2434c3a]
.Use a single backtick before and after inline literals
[%header]
|===
|No |#Yes#
|[.line-through]#The example below shows the structure of an `++``Act``++`.#
|The example below shows the structure of an `++Act++`.

|[.line-through]#Movements of vehicles in `++``Act``++` are defined in the `++``ManeuverGroup``++ `` s section.#
|Movements of vehicles in `Act` are defined in the section `ManeuverGroup`.
|===

*Source*

ASAM Writing Guide: 6.1. Inline literals


[#sec-ASM-79]
== Use four space characters per indentation level for source code blocks (ASM-79)

* Do not use tab characters.

*Exceptions*

There are no exceptions.

*Example*

[#tab-17223b72-a10c-4053-be85-e1fd3340533b]
.Use of four space characters per indention level (space characters marked as '.')
[%header]
|===
|No |#Yes#

a|[source, xml]
<planView>
..<geometry x="-0.014"
............y="-0.055"
............hdg="2.88"
............length="95.89"
............s="0.0">
....<arc curvature="-0.000490572"/>
a|[source, xml]
<planView>
....<geometry x="-0.014"
..............y="-0.055"
..............hdg="2.88"
..............length="95.89"
..............s="0.0">
........<arc curvature="-0.000490572"/>
|===

*Source*

ASAM Writing Guide: Indentation

[#sec-ASM-53]
== Indent XML attributes in examples (ASM-53)

* If XML attributes in examples lead to extra long lines, insert line breaks and indent the XML attributes to form a column under the first XML attribute.
* Place one XML attribute per line.

*Exceptions*

There are no exceptions.

*Example*

[#tab-4bcfeb0d-373c-47c3-8b0b-286cbcd6c4a2]
.Indent XML attributes in extra long lines (space characters used for indention marked as '.')
[%header]
|===
|No |#Yes#

a|[source, xml]
<planView>
....<geometry x="-0.014" y="-0.055" hdg="2.88" length="95.89" s="0.0">
........<arc curvature="-0.000490572"/>
a|[source, xml]
<planView>
....<geometry x="-0.014"
..............y="-0.055"
..............hdg="2.88"
..............length="95.89"
..............s="0.0">
........<arc curvature="-0.000490572"/>
|===

*Source*

ASAM Writing Guide: Indentation



[#sec-ASM-121]
== Mark up ASAM XML elements (ASM-121)

* For XML elements, use the name of the element in angle brackets (`++<>++`) and backticks (`++``++`), and afterwards the word "element" or "elements".
* For attributes, use the at symbol (`++@++`) and the name of the element.
Optional: Use the words "attribute" or "attributes".
* Do not use the plural of the name of XML elements or attributes.

*Exceptions*

This exception reflects the current implementation in ASAM OpenSCENARIO.
The documentation of ASAM OpenSCENARIO shall be aligned with the definition in the ASAM Editorial Guide in a future project.

* For XML elements, use the name of the element in backticks (`++``++`).
Optional: Use the words "instance" or "instances".
* For XML attributes, use the name of the attribute in backticks (`++``++`).
Optional: Use the words "attribute" or "attributes".
* For values, use double quotation marks (" ").
* Do not use the plural of the name of XML elements or attributes.

*Example*

[.underline]#Code#

++`++<roadMark>++`++ element

[.underline]#Result#

`<roadMark>` element

[#tab-290d36d7-08a5-4aac-9ba2-7e60db7d448a]
.Mark up ASAM XML elements
[%header]
|===
|No                                  |#Yes#
|[.line-through]#road mark element#  |`<roadMark>` element
|[.line-through]#``<roadMark>``s#    |`<roadMark>` elements
|[.line-through]#type#               |@type
|[.line-through]#`<type>` attribute# |@type attribute
|[.line-through]#``<type>``s#        |@type attributes
|===

*Source*

ASAM specific rule.
