= How-To: Review a standard (public release candidate)
:description: Describes how to review a standard.
:keywords: review, service-desk, REVIEWED_OK

include::partial$_attributes.adoc[]
include::{abb}[]

//tag::body[]

[cols="1,5", grid = rows]
|===
h|Responsible
| {role-reviewer}, {role-standard-user}

// h|Involved
// | {role-gtm}

ifdef::compendium[]
h| Phase
| xref:getting-involved:review_phase.adoc#_process_overview[image:compendium:asam/project_lifecycle-review.svg[]]
endif::[]

h| Step
// | image:compendium:asam/proposal_phase_v2-proposal_workshop.svg[]
| TODO

h|TL;DR
a| * TODO

|===

// - internal reviews: within group --> discuss and decide in group
// - ASAM public reviews: review with ASAM members -->
// - public reviews: public and open review -->

== Context
Standardization requires constant reviewing of its documents.
Some projects have a public release candidate.
These can be reviewed by any person without having to be an ASAM member.

If a document or documents is released as a public release candidate, it is announced through the https://www.asam.net/newsletter/[newsletter^] and the https://www.asam.net/active-projects/public-review/[ASAM website^].

This review occurs at the end of a standardization project and is optional.

This description is intended for all people interested in giving feedback for such a review document, independent of ASAM membership status.

== Result
Comprehensive and comprehensible feedback has been submitted to the project group on the review document(s).

== Prerequisites
* Documents must be a public release candidate

== How
. Access the "Public Review" page (through the website or the newsletter)
. Select the standard you would like to review to be forwarded to its review page
. Read through the document(s) carefully
. Provide feedback on the relevant page through the integrated "Submit feedback" button or sending an email to the provided review address using the xref:compendium:Templates/review_feedback_template.adoc[]

NOTE: The sent email creates a new issue in the ASAM remote repository using the GitLab Service Desk feature.
You can find more information on using GitLab Service Desk under xref:compendium:How-Tos/how-to__review_with_gitlab_service_desk.adoc[].

// ASAM uses the following feedback tools:
// include::tooling:partial$review_tools.adoc[]

// == Troubleshooting / Known Issues
//end::body[]