= How-To: Submit Candidacy For Project Lead
:description: Describes how to submit a candidacy for Project Lead.
:keywords: proposal, project-lead

include::compendium:partial$_attributes.adoc[]

//tag::body[]

[cols="1,5", grid = rows]
|===
h|Responsible
|{role-wg-member} -> {role-project-lead}

h|Involved
|{role-gtm}

ifdef::compendium[]
h| Phase
| xref:getting-involved:proposal_phase.adoc#_process_overview[image:compendium:asam/project_lifecycle-proposal.svg[]]
endif::[]

h| Step
| Any time during the proposal phase

h|TL;DR
a| * Send an email to your {gtm} containing your candidacy for Project Lead

|===

NOTE: This page covers how to submit candidacy for the role of xref:role-specific:project-lead.adoc[Project Lead]. +
If you want to learn more about the role of the Project Lead and its requirements, see xref:getting-involved:signing_up/become_project_lead.adoc[].


== Context
Every project at ASAM needs a Project Lead.
Consequently, a project may only move from Proposal phase to Standard Development phase if at least one project member has declared their candidacy for Project Lead. +
In most projects, the Idea Giver candidates for Project Lead, but this is not a requirement.


include::role-specific:partial$role_responsibilities.adoc[tag=project-lead]

== Result
You have submitted your candidacy for the role of Project Lead.


== Prerequisites
* You must be a project member
* You accept the xref:role-specific:project-lead.adoc[**responsibilities and expectations**] for this role


== How
* Send an email to your GTM with your candidacy for the role of Project Lead


== What Happens Next
The Project Lead is officially decided at the beginning of the project, if the Proposal has been approved by the TSC. +
If there is more than one candidate, the project will then decide on the Project Lead.
Otherwise, the single candidate is just confirmed formally by the project.


See also xref:role-specific:project-lead.adoc[].

//end::body[]