= Identify the need for Service Providers
:description: How to identify the need for Service Providers.
:keywords: service-provider, proposal


include::compendium:partial$_attributes.adoc[]

{how-to-icon}



//tag::body[]

[cols="1,5", grid = rows]
|===
h|Responsible
| {role-proposal-submitter}

h|Involved
| {role-project-participant}

ifdef::compendium[]
h| Phase
| xref:getting-involved:proposal_phase.adoc#_process_overview[image:compendium:asam/project_lifecycle-proposal.svg[]]
endif::[]

h| Step
| TODO

h|TL;DR
a| * TODO

|===

NOTE: This page covers identifying the need for Service Providers in a project. +
If you are looking for how a Service Provider is selected, see xref:getting-involved:development/engage_service_provider.adoc[]. +
If you are a Service Provider looking for information on your role, refer to the xref:role-specific:service-provider.adoc[Service Provider role description].

== Context

It is possible a project's list of required expertise cannot be fully covered by the project members themselves.
This may be

* insufficient resources (people, time) on the participants' side.
* missing technological knowledge regarding some aspects the project's subject.
* the need for a specialized project organizer.
* model creation.
* the role of a technical writer and editor.

In those cases, a project may decide to hire one or more Service Providers to fill these roles.

== Result
* The need for Service Providers is identified and quantified
* If the project needs Service Providers, a list of requirements and job descriptions is created


== How
TODO

//end::body[]

related::service-provider[]
