= Join a Proposal Workshop
:description: Describes how to join a Proposal Workshop.
:keywords: proposal, proposal-workshop

include::compendium:partial$_attributes.adoc[]

{how-to-icon}


//tag::body[]

[cols="1,5", grid = rows]
|===
h|Responsible
| {role-member} / {role-standard-user} -> {role-project-participant}

h|Involved
| {role-gtm}

ifdef::compendium[]
h| Phase
| xref:getting-involved:proposal_phase.adoc#_process_overview[image:compendium:asam/project_lifecycle-proposal.svg[]]
endif::[]

h| Step
| image:compendium:asam/proposal_phase_v2-proposal_workshop.svg[]

h|TL;DR
a| * Sign up through the https://www.asam.net/conferences-events/upcoming-events/[ASAM website^]

|===

[horizontal]
Current Proposal Workshops:: https://www.asam.net/conferences-events/upcoming-events/[ASAM website^]

NOTE: This page covers how to join a proposal workshop.
If you are the Idea Giver and looking for how to prepare a workshop, check out xref:getting-involved:proposal/proposal_workshop_preparation.adoc[] instead.

== Context
You are interested in an upcoming project?

include::compendium:page$Templates/proposal_workshop_gameplan.adoc[tag=context]

Additionally, you can also present your view on the project idea.
If you are interested in doing so, contact the mailto:info@asam.net[ASAM Office] before the event.

You can also xref:getting-involved:signing_up.adoc[sign up for a project participation], both for the Proposal and the xref:getting-involved:development_phase.adoc[Standard Development phase] (if the project is agreed upon by the TSC).

== Goals of the Proposal Workshop
include::compendium:page$Templates/proposal_workshop_gameplan.adoc[tag=goals]

== Result
You have signed up for the selected proposal workshop.

== How
. Go to the https://www.asam.net/conferences-events/upcoming-events/[ASAM website^] and find the proposal workshop you are interested in.
. Access the "Registration" tab, fill out the form and send it to register. +
You will receive a confirmation email if your registration was successful.

== Troubleshooting / Known Issues
=== I cannot find the event online, but I know it exists
If you want to join a project proposal but cannot find the event on the website, you can also contact mailto:info@asam.net[ASAM Office] directly.
Please consider this as a last resort to fall back to only in case you cannot find the information.

//end::body[]

related::proposal-workshop[]