= Create a project's Proposal document
:description: How-to for creating a new project proposal from an executive draft
:keywords: proposal

include::compendium:partial$_attributes.adoc[]

{how-to-icon}


//tag::body[]
//tag::roles[]
[cols="1,5", grid = rows]
|===
h|Responsible
| {role-idea-giver}

h|Involved
| {role-project-participant}, {role-or}

ifdef::compendium[]
h| Phase
| xref:getting-involved:proposal_phase.adoc#_process_overview[image:compendium:asam/project_lifecycle-proposal.svg[]]
endif::[]

h| Step
| image:compendium:asam/proposal_phase_v2-proposal_writing_draft.svg[]

h|TL;DR
a| * Write the Motivation section
* Define use cases
* Refer to known existing standards
* Fill in all technical chapters
* Discuss and optimize together with ASAM Office

|===
//end::roles[]

// If you use a recurring image for similar artifacts, declare it as attribute in partials/_attributes.adoc and reference here.

TIP: The ASAM Office assists the writer(s) by giving advice with respect to ASAM guideline and best practices.

== Context
In case a new project is proposed, the first step is to create an Executive Draft for internal analysis. +
Based on this draft, a rough Proposal Draft is then created that contains further details needed for the Proposal Workshop.
This Proposal Draft is later further expanded and detailed until it is ready for submission to the TSC.

TIP: The more details you add initially, the easier it is for ASAM to understand and support your proposal and the deeper and more focussed the discussions in the workshops will be.

== Result
A valid Project Proposal is created that can be brought to decision by the TSC.

NOTE: The final Project Proposal document is generated based on Asciidoc files, but the initial executive draft may be a Word document.
For proposal submission, the proposal document must be converted into the appropriate Asciidoc structure.

== Prerequisites

* The idea has been proposed and approved in the xref:getting-involved:ideation_phase.adoc[Ideation Phase].
* The proposal needs at least three (3) partner companies.

== How
. Access the project's online repository through the link provided by your OR
.. Optionally, check out the project repository or download the https://code.asam.net/common/templates/proposal-template[Executive Draft template^] and edit the AsciiDoc files directly. +
+
IMPORTANT: You must update the content of each chapter's issue regardless of if you write in the AsciiDoc files directly or not!
. Fill in the default structure as follows (in the respective issues):
.. Add a comprehensive 'Executive Summary' outlining the general idea of the proposed project
.. Describe the reasons for this proposed project in the 'Motivation' section
.. Define a set of (initial) use cases in the 'Use Cases' section
.. (OPTIONAL) If you know of other standards this proposal relates to (ASAM or other), list them in the 'Relations to Other Standards or Organizations' section
. (OPTIONAL) Create an initial structure for the section 'Technical Content' and fill write as much project specific content as possible
. Discuss and optimize the document with your OR
. Transfer the issues' content to the project's AsciiDoc files.
The OR will support you with this task, if needed.
Note that you do not need to render the document manually.
The repository's pipeline will create the required documents as artifacts automatically when the changes are committed and pushed to the trunk.
See xref:compendium:How-Tos/access_compiled_artifacts.adoc[] to learn more about pipeline artifacts and how you can access them.

NOTE: The sections 'Project Resources' and 'Project Plan' will be filled out at a later stage and do not need to be edited in this draft.

//end::body[]