= Use GitLab service desk for reviews
:description: Describes how to use the service desk in GitLab for reviews.
:keywords: gitlab, service-desk, review

include::compendium:partial$_attributes.adoc[]

{how-to-icon}


{role-standard-user}
{role-project-participant}


== Create issue through service desk

//tag::body[]
Users can create issues and provide feedback in supported projects by using the GitLab https://docs.gitlab.com/ee/user/project/service_desk.html#using-service-desk[service desk].
The service desk is a feature where issues are created by incoming emails.

The email adress is provided separately.
If you cannot find it, send a request to mailto:info@asam.net[].

IMPORTANT: Do not send your feedback directly to info@asam.net.
Any project feedback sent to this address will be discarded.

If the project uses Antora, the template is available through the "Submit feedback" button on the top of each page.

TIP: Use the button on the correct page to automatically add the page name and further meta information to your feedback.

=== How
//tag::steps[]

. If using Antora: Click the button "Submit feedback"
. Add a title in the email.
This will be the name of the issue you create.
. Replace all `<text>` placeholders
+
include::compendium:page$Templates/review_feedback_template.adoc[tag=body]
+
. Send the email

//end::steps[]

//end::body[]




If you want to send an email manually (i.e. not through the "Submit feedback" button), please format your feedback using the provided <<standard-review-template>> (see example above).

related::service-desk[]