= Setup project development repository
:description: Describes how to set up a new development project.
:keywords: development, setup

include::compendium:partial$_attributes.adoc[]

{how-to-icon}


//tag::body[]
//tag::roles[]
[cols="1,5", grid = rows]
|===
h|Responsible
| {role-or}

h|Involved
| {role-project-participant}

ifdef::compendium[]
h| Phase
| xref:getting-involved:development_phase.adoc#_process_overview[image:compendium:asam/project_lifecycle-development.svg[]]
endif::[]

h| Step
| image:compendium:asam/development_phase-repo_setup.svg[]

h|TL;DR
a|* Fork the https://code.asam.net/common/templates/standard-template[**standard template repository**^] as "<project-name> <type-suffix>"
* If necessary, update project-name sub-group members
* Inform members
|===

//end::roles[]

== Context
The basis for most development projects at ASAM is GitLab.
However, some projects may choose to use GitHub instead.
The basic procedure stays the same, independent of the platform that is used. +
In order for project members and the Project Lead to work on their respective project, a new development repository has to be created.


== Result
* A new repository in the existing project sub-group has been created and the link been provided to all current project members.
* The repository name is "<project-name> <type-suffix>", where "<project-name>" is the name of the project (e.g. "OpenDRIVE") and "<type-suffix>" is the current xref:concepts:project_types.adoc[project type] (e.g. "Standard").


== Prerequisites
* The idea has been proposed and approved in the xref:getting-involved:ideation_phase.adoc#_process_overview[Ideation Phase].


== How
IMPORTANT: In order to be able to fork a project into a group, you must be a member with sufficient rights in this group.

. If this is the first time this xref:concepts:project_types.adoc[project type] is used for this project:
.. xref:compendium:How-Tos/forking_repo.adoc[Fork] the latest version of the https://code.asam.net/common/templates/standard-template[**standard template repository**^] into the existing sub-group for the project.
* The structure of the repository is explained in the included README
.. Rename the forked project to "<project-name> <type-suffix>", where "<project-name>" is the name of the project (e.g. "OpenDRIVE") and "<type-suffix>" is the current xref:concepts:project_types.adoc[project type] (e.g. "Standard").
.. Set the project visibility to "Internal"
.. Set the Merge request settings to "Fast-forward merge" and check the boxes for "Pipelines must succeed" and "All discussions must be resolved".
Also, make sure to set the "Target project" for Merge Requests to "This project"
.. Under "Advanced", change the end of the path to "<project-name>-<type-suffix>", replacing "<project-name>" and "<type-suffix>" accordingly
.. Follow the instructions in the https://code.asam.net/common/templates/standard-template/-/blob/master/README.adoc[**template repository's README**^]
.. If the project requires more than one repository, repeat step 1, but this time fork from the created central repo instead of the template
. Update the assigned members of the sub-group according to the currently enrolled members.
Tip: Use https://code.asam.net/internal/gitlab-member-management/-/blob/master/create_users_and_update_group_members_from_csv.py[this python script^] to automate the process based on an exported csv from the Project participants list.
This only works for GitLab, though.
. Send a mail with the link to the new project to the proposal members, informing them that the repository is now ready for use.

//end::body[]