= Docker
:description: A summary page describing what Docker is and where to find related information, guides etc.
:keywords: docker,summary,tool,recommended, doc-as-code

include::partial$_attributes.adoc[]


include::compendium:partial$icon_reminder.adoc[tag=download-link]


// {role-technical-writer}
// {role-service-provider}

//tag::summary[]
Docker is a platform where you use so-called containers to run applications in an encapsulated environment.
With this, you do not need to install and configure software, programming languages etc: just download and use a pre-configured container that has all the relevant configuration already built in.
From the docker homepage:

> Docker is an open platform for developing, shipping, and running applications.
Docker enables you to separate your applications from your infrastructure so you can deliver software quickly.
With Docker, you can manage your infrastructure in the same ways you manage your applications.
By taking advantage of Docker’s methodologies for shipping, testing, and deploying code quickly, you can significantly reduce the delay between writing code and running it in production.

image::https://docs.docker.com/engine/images/architecture.svg[title="The Docker link:https://docs.docker.com/get-started/overview/#docker-architecture[architecture]", link="https://docs.docker.com/get-started/overview/#docker-architecture", window=_blank]
//end::summary[]


== Docker at ASAM
For Asciidoctor and Antora, Docker can be used to run a pre-configured setup for creating output locally.
This removes the need to upload adoc files and use the build pipeline for every change you want to see. +
To render a project's documentation without having to upload it, use Docker Compose with a correctly defined docker-compose.yml file.

For information on what YAML/yml means, see https://de.wikipedia.org/wiki/YAML[YAML on Wikipedia^]

== Content

[cols="^1h,4",frame=none, grid=rows, stripes=hover]
|===

|xref:compendium:Tools/docker/01_docker_setup.adoc[image:{setup-image}[width=120,title="Docker setup"]]
|Docker Setup

|xref:compendium:Tools/docker/02_docker_guides.adoc[image:{guide-image}[width=120,title="Docker guides"]]
|Docker Guides

|xref:compendium:Tools/docker/03_docker_best-practices.adoc[image:{best-practices-image}[width=120,title="Docker best practices"]]
|Docker Best Practices

|===

// related::antora,asciidoctor[]