= Sharepoint structure
:keywords: teams, sharepoint

Every project at ASAM uses the same base folder structure for its Sharepoint.
It also serves as a project's landing page (webpage) for the group where news are shared, FAQs are hosted, and important links and files can be found.

NOTE: You can use Sharepoint online or https://support.microsoft.com/en-us/office/sync-sharepoint-files-with-the-onedrive-sync-client-groove-exe-59b1de2b-519e-4d3a-8f45-51647cf291cd[synch it locally^].

include::compendium:Guidelines/coordination-teams-channel_file-structure.adoc[tag=body]


== What Sharepoint is used for
In ASAM projects, Sharepoint is used to exchange information in the team that is not a direct result or content of development.
It consists of a landing page specific to the project and may be extended by the group as they see fit.

In addition to the landing page and its webpage features (such as FAQs), the main aspect of Sharepoint is its documents storage.
Sharepoint can be used to exchange files not directly used as project content (e.g. background information, studies, floor plans for meetings etc.).
It also contains the approved project proposal as well as the current <<Participants list,participants list>>.

The Sharepoint also contains a current controlling overview for any involved external parties.


== What Sharepoint is NOT used for
Any content directly relevant to the project's deliverables (such as images to be used in a standard) are not to be organized through Sharepoint.
Instead, such information has to be entered through the project's repository so that is subjected to the same version control as all the other content.
The same is true for meeting notes, which are to be taken as repository issues.


== Participants list
Sharepoint contains a list of all participants in the related project.
This list is set up initially based on the signups during the Proposal phase.

However, participation and assignments may change during development. +
It is the responsibility of the Project Lead to keep this document up to date on at least a monthly basis.
They may delegate this task to another project member.
