= Project types
:description: Describes the different project types at ASAM for new members and interested parties.
:keywords: project, type, asam, concept

include::partial$_attributes.adoc[]


== Overview
ASAM develops its products and results in projects.

Different projects entail different expectations towards the type of deliverables, although the quality expectations remain {description}

ASAM project types and the expected deliverables are:

* For a **concept project**, the output is a Concept Paper (which can be the basis for a follow-up project)
* For a **standard development project**, the output is the standard + optional supplemental documents
* For a **study project**, the output is a Study Report that details the findings of the project.
* For an **implementation project**, the output is software, tooling or reference implementations to support the use and adoption of one or more standards.

image::Concepts/project_types_overview.drawio.svg[title="ASAM project types overview", width= 800]



// TODO: Project types need to be discussed by TSC first.

== Details
[tabs]
====
Concept::
+
--
[horizontal]
Description:: 
Concept projects are chosen to clarify scope, use cases and requirements towards potential standardisation projects. This may include technology surveys or the carrying out of performance benchmarks.

Output:: Concept paper
--
Standard development::
+
--
[horizontal]
Description:: 
Development of a new version or versions for a standard in accordance with the demands of ASAM members and market requirements.

The versioning of standards is described in the link:https://internal.pages.asam.net/asam-editorial-guide/editorial-guide-generator/editorialguide-word/1.0.0/Editorial_guide/01_basics.html#sec-ASM-14[ASAM Editorial Guide]

Output:: Standard


--
Study::
+
--
[horizontal]
Description:: Study projects provide members an organizational structure to study or analyze specific aspects of ASAM standards or technology sectors in a collaborative way.

These activities aim to improve understanding of using and implementing ASAM standards, the overall landscape and to identify potential new areas for standardization.

Output:: Study report

--
Implementation::
+
--
[horizontal]
Description:: Create a supplementary product to a standard that supports the implementation or application of an ASAM standard in the industry. 

Repository suffix:: Implementation
Output:: Software tools or scripts, such as checkers, reference implementations, plugins, etc.
--
====
