= Build Antora locally
:description: Describes how to build antora locally on you pc without needing to run the CI/CD on GitLab.
:keywords: antora,guide,docker

include::contributing:partial$_attributes.adoc[]
include::compendium:partial$_attributes.adoc[]

{how-to-icon}


== Context
This guide explains how to build Antora projects locally on your PC without having activated the ASAM build pipeline.

== Result
The Antora output has been built locally.

== Prerequisites
* {docker-icon-norole} {docker-url}[Docker^] must be installed and running.
* To use the provided script, https://www.python.org/downloads/[Python^] must be installed (during installation, check the box "Add Python [version] to PATH").
* The generator repository for your project has been checked out.
For development projects, the generator repository is located here: https://code.asam.net/internal/examples/antora-base-repo-example[window=_blank]

== How
. Check the generator's 'site.yml' configuration
* For local builds, the url under content/sources must be local.
Typically, this is "./foldername", where "foldername" is the name of the folder the content was checked out into
* Ensure that you use the branches and/or tags you want to build
. Run the _scripts/build.py_ Python script: `python scripts/build.py`
+
-> The generated page automatically opens in the browser (Chrome).
+
* To build the content without opening it automatically, add `-s` after "build.py"
* To reopen the last build, add `-f` after "build.py"
* To get more information on possible options, type `-h` after "build.py"

== Example for site.yml
The example below shows the differences between a remote build setup and a local build setup.
All changes are applied in the project's site.yml.

[tabs]
====
Remote build::
+
--
Build using the GitHub repository, the branches "main" and "pre-restructuring", and all tagged versions starting with "v".
Use the folder "content" in the repository for this content source.

[source, yaml]
----
content:
  sources:
    - url: https://github.com/asam-ev/asam-project-guide-content.git
    # - url: ./asam-project-guide-content
      branches: main, pre-restructuring
      # branches: main
      tags: v*
      start_path: content
----
--
Local build::
+
--
Build using the local folder "asam-project-guide-content" and only the branch "main".
Use the folder "content" in the repository for this content source.

[source, yaml]
----
content:
  sources:
    # - url: https://github.com/asam-ev/asam-project-guide-content.git
    - url: ./asam-project-guide-content
      # branches: main, pre-restructuring
      branches: main
      # tags: v*
      start_path: content
----
--
====

== Troubleshooting / Known Issues
=== Antora tells me there are duplicate files
The most likely reason here is that you are trying to build two separate branches or tags that have identical component descriptors (typically, these are named "antora.yml").
The default component descriptor applies automatic versioning based on git values.
However, some configuration may lead to two separate branches or tags getting the same version in Antora.
In this case, update at least one of the impacted component descriptors so that its version is different from the other.
To do so, you can either set a manual value or update the rules that are applied the refname.

=== The python script does not execute all the steps
The script must be executed from the correct folder.

. Navigate to the folder where the script is located.
. Open a terminal window
. Execute 'python build.py'

=== I don't want to/cannot use python
Unfortunately, there are some features that will not be available without python (i.e. the custom macros and summary features).
If you cannot use python for whatever reason, you may use a python docker container and run everything from within there.

=== The Antora generator does not work anymore
If you had already set up the Antora image with the one-time step `docker-compose build antora` before and it stopped working, there is a chance that some technical changes have been made.
To switch to the newest setup,

. run 'docker-compose down' to stop any currently running docker-compose,
. delete the image related to the project-guide antora setup (e.g. "asam-project-guide_antora") with the `docker rmi` command (see `docker rmi --help` for more information) +
+
NOTE: You might need to force the deletion!

. prune the volume used by antora
. re-do the "<<only-required-once,only required once>>" steps

=== I changed my content but I do not see it in Antora
Any program that blocks the site folder will stop Antora from generating the new pages.
The reason is that it needs to delete the existing folder first before the new content is then written into it.
Make sure that no program is currently accessing and blocking files or folders from the "./site" path.
Tools that are unproblematic:

* Windows Explorer
* Google Chrome