= Enroll for project development
:description: Describes how to enroll for a project's development phase.
:keywords: enrollment, development, proposal
:compendium:

//tag::body[]
include::compendium:partial$_attributes.adoc[]
//end::body[]

{how-to-icon}


[cols="1,5", grid = rows]
|===
h|Responsible
|{role-member}

h|Involved
| {role-or}

// ifdef::compendium[]
// h| Phase
// | xref:getting-involved:ideation_phase.adoc#_process_overview[image:compendium:asam/project_lifecycle-ideation.svg[]]
// endif::[]

// h| Step
// | image:compendium:asam/ideation_phase-ideation_propose.svg[]

h| TL;DR
a| * Contact the ASAM office and provide the required information:
** project
** commitment
** your participants
** each participants role

|===

//tag::body[]

== Context
You are interested in joining an ASAM project for active development?
Follow the steps below.


== Result
You have signed up for and committed to the chosen project.


== Prerequisites
* You must be an ASAM member to join a project
* Your commitment must be at least 50% of the project group's average

NOTE: Enrollment is possible in the period between the xref:getting-involved:proposal/phase_details.adoc#_proposal_workshop[Proposal Workshop] and the xref:getting-involved:development/phase_details-setup.adoc#_kick-off_workshop[Kick-off Workshop]. +
In case you need to join after this period, contact the ASAM office. 
The ASAM CTO can make an exception if the reasons for joining after the fact are sufficiently important. 
The same is true if you cannot commit the required amount.

== How

. Contact the ASAM office (through the project's https://www.asam.net/active-projects/proposals/[proposal webpage^]) with your request to enroll
* Enclose all mandatory information in the contact form
* Consider the provided minimal and recommended minimum contribution
. You will receive a confirmation
.. In case your project commitment is below the minimum value, you will be contacted by the office to check if you will increase your commitment or withdraw your enrollment

//end::body[]

