= ASAM Project Guide
:description: The main landing page for the ASAM Project Guide.
:keywords: main, home, start
:page-aliases: home.adoc

include::partial$_attributes.adoc[]


Welcome to the **ASAM Project Guide**!

****
IMPORTANT: This guide is a work in progress and subject to change!
****


This guide provides an introduction to new members on ASAM in general and its most central topics, gives an overview on how to get involved and provides role-specific information for working at ASAM and in ASAM projects. +
In addition to that, it also contains a full explanation on each and every process and workflow applied in ASAM projects, contains guides on suggested tools as well as a compendium on specific tasks and topics. +
Lastly, you can also find information and guides on how to participate in improving this Project Guide.

NOTE: This guide assumes you already know who and what ASAM is.
For more information, refer to the https://www.asam.net/about-asam/[ASAM website^].


== Quick access

include::partial$landing_page_referral.adoc[tag=body]


// IMPORTANT: This version contains the rules and information relevant to each project by default.
// Some projects can decide to steer away from the standard development path by developing a variation on the standard set of rules layed out here.
// These changes must be discussed with and accepted by ASAM Office first. +
// Any project with specific alterations gets a project-specific variant of this guide.
// You can access different versions in the dropdown menu at the bottom-left.