= ASAM Project Guide
:description: The main landing page for the ASAM Project Guide.
:page-aliases: home.adoc

include::partial$_attributes.adoc[]

Welcome to the **ASAM Project Guide**!

NOTE: This guide is a pre-release and constantly being updated.
Feel free to submit any feedback you have using the btn:[Submit feedback] button.
If you need to reference a specific version of this guide, make sure to select that version from the version selector at the bottom left.

ASAM tries to keep technical requirements for participation as low as possible.
There is no need to install any software to be able to participate.
All the tools most project members need in their projects are hosted online.
They can be accessed through any standard web browser. +
The only thing needed to get started is an account.
To get help with getting setup, follow the xref:tour_guide:index.adoc[guided tour].

If you have any questions or feedback, do not hesitate to contact the xref:compendium:Project guidelines/01_project_terms.adoc[ASAM Office Responsible (OR)].

NOTE: This guide assumes prior knowledge of who and what ASAM is.
For more information, refer to the https://www.asam.net/about-asam/[ASAM website^].


This guide provides two entry points:

[horizontal]
xref:tour_guide:index.adoc[Guided tour]:: A walkthrough of all relevant basics to get you up and running for your ASAM project.

xref:compendium:main.adoc[Compendium]:: A searchable collection of relevant individual topics
