= ASAM Project Introduction
:description: The main landing page for the ASAM Project Introduction.
:page-aliases: home.adoc

include::partial$_attributes.adoc[]


Welcome to the **ASAM Project Introduction**!

This guide provides an introduction to new members on how to get involved.
It provides an overview over all relevant basics to get you up and running for your ASAM project.

ASAM tries to keep technical requirements for participation as low as possible.
One example is that you do not need to install any software on your computer to be able to participate.
All the tools most project members needs in their project are hosted online.
They can be accessed through any standard web browser. +
The only thing you need to set up is your account.
To get started, follow the xref:tour_guide:index.adoc[guided tour].

If you have any questions or feedback, do not hesitate to contact your ASAM Office Responsible.

NOTE: This guide assumes you already know who and what ASAM is.
For more information, refer to the https://www.asam.net/about-asam/[ASAM website^].

== Quick access

include::partial$landing_page_referral.adoc[tag=body]
