= Writing a Project Proposal
:description: Summarizes steps for contributing to a project proposal
:keywords: proposal

include::partial$_attributes.adoc[]


[cols="1,5", grid = rows]
|===
h|Responsible
| {role-idea-giver}, {role-project-participant}

h|Involved
a| {role-or}

h| Steps
| image:compendium:asam/proposal_phase_v2-proposal_writing.svg[]

h| TL;DR
a| * All participants contribute content through issues
* Issues are transferred to AsciiDoc files by dedicated writers
* Before the Proposal Workshop, a complete project and feature description must be present
* After the workshop, the Proposal is finalized by including the feedback from the Workshop, defining the timeline, adding the list of participants, and calculating the proposed budget.

|===


== The proposal document
The Project Proposal is a written document that is submitted to the TSC for project approval before any project at ASAM may start. +
All committed participants (the Idea Giver, the Proposal Submitter, and all prospective Sub-group Members) can participate in writing the proposal document (the Proposal Submitter actually has to participate in the <<Finalizing the Proposal,finalization step>>). +
See **xref:getting-involved:proposal/proposal_document.adoc[]** for more information on the document and its intended contents.


== How to contribute
IMPORTANT: You must first complete the xref:contributing:main.adoc#_minimum_required_setup[**Minimum Required Setup**] before you can participate in and contribute to any project. +
Participation in the creation of a Project Proposal follows the central xref:compendium:Guidelines/workflow-trunk.adoc[**Trunk-based Workflow**] at ASAM.
If you want to learn more about this workflow, click the link.

To contribute to a Project Proposal, project members can either <<Contributing through issues,contribute through GitLab issues>> or <<Contributing in AsciiDoc,contribute directly in AsciiDoc>>.
However, at least one person must transfer all content to the AsciiDoc file eventually. +
Both ways of contribution can be performed xref:contributing:main.adoc[without software installation] directly through the respective web interface.
If you prefer to work on your local computer, see the xref:contributing:main.adoc#_recommended_tools[list of recommended tools].


=== Contributing through issues
{mandatory}

The content of a Proposal document shall be drafted and discussed through issues in the project's issue board. +
ASAM provides guidelines on how to contribute through issues on the page **xref:compendium:Guidelines/proposal_phase_contribution_guidelines.adoc[]**.
All participants must follow these guidelines.

=== Contributing directly in AsciiDoc
{optional}

The project may decide to contribute directly in AsciiDoc as well.
However, content shall still be discussed and updated in issues as described in <<Contributing through issues>>.

When writing AsciiDoc, writers must follow the guidelines described in **xref:compendium:Guidelines/workflow-contribute_in_asciidoc.adoc[]** as well as the <<ASAM Editorial Guide>>.

=== Transferring content to AsciiDoc
{mandatory}

The content that is defined in the project's issues must be transferred to AsciiDoc eventually.
ASAM recommends that the project defines one or more writers responsible for this task.

When writing AsciiDoc, writers must follow the guidelines described in **xref:compendium:Guidelines/workflow-contribute_in_asciidoc.adoc[]** as well as the <<ASAM Editorial Guide>>.


=== ASAM Editorial Guide
ASAM provides an Editorial Guide containing the writing guidelines applicable to all ASAM documents.
The current version of the Editorial Guide is located in the xref:compendium:Editorial_guide.adoc#_basics[**Project Guide Compendium**].

The Editorial Guide is **mandatory** for all Technical Writers and **recommended** for users contributing content through issues.

// == Creating the executive summary

// include::compendium:page$How-Tos/executive_draft.adoc[leveloffset=+1, tags=body]


== Writing the Proposal draft

include::compendium:page$How-Tos/proposal_writing.adoc[leveloffset=+1, tags=body]


== Finalizing the Proposal

[cols="1,5", grid = rows]
|===
h|Responsible
|
h|Involved
| {role-project-participant}, {role-or}

h| Step
| image:compendium:asam/proposal_phase_v2-proposal_writing_finalization.svg[]

h|TL;DR
a| * Create the xref:getting-involved:proposal/proposal_document.adoc#_project_timeline[milestone plan]
* Finalize content for submission
* Review content with proposal team
|===
Once the Proposal Workshop has taken place, the Proposal must be finalized. +
To do so, the Proposal Submitter (and all other involved writers) shall consider the following input for finalizing the project proposal:

- the existing Proposal draft
- meeting minutes of the xref:getting-involved:proposal_phase.adoc#_proposal_workshop[Proposal Workshop]
- relevant papers from concept projects (if any)

The Submitter shall estimate the work efforts of the project and create a xref:getting-involved:proposal/proposal_document.adoc#_project_timeline[milestone plan].
include::getting-involved:partial$milestone_plan_duration.adoc[]

The Office then checks the proposal document for formal compliance and understandability.

The proposal may contain a request for video conferencing support through the Office, if project group members originate from locations that would require long-distance (i.e. inter-continental) business trips to regularly participate at project meetings. +
The Submitter shall send out the proposal to all participants of the Proposal Workshop (if this occurred) for review before xref:getting-involved:proposal/submit_proposal.adoc[submitting it].
