= Adding a page
:description: Explains how to add a new page to the Project Guide and what to look out for.
:keywords: page,project-guide,new_content
:page_template_name: template-default-page.adoc
:page_template_alt_name: default page template
:page-aliases: adding_content/add-a-page.adoc

include::partial$_attributes.adoc[]


{add-file-icon}

== Context
In order to make documented pages easier to understand, it is necessary to have a standard format for pages in which they are written.
For this purpose, the xref:ROOT:attachment${page_template_name}[{page_template_name}] file was created.
Each page that is documented in this Project Guide shall use the {page_template_alt_name}.

NOTE: If you want to define a reusable content, consider using a xref:adding_content/add-a-partial.adoc[Partial] instead.
See xref:adding_content/pages-vs-partials.adoc[] for more information on the difference between those two.

== Result
A page is created that follows the ASAM {page_template_alt_name}.

== Prerequisites
none

== How
IMPORTANT: These instructions already include the requirements of https://docs.antora.org/antora/latest/page/standard-page/[Creating A Standard Page^] by Antora implicitly.
However, if one deviates from this guide here, the Antora restrictions and requirements still apply!

. Find the module you want your page to be located in.
. Create your file in the "pages" folder or move it there
.. Alternatively, create a new folder and/or add your file to an existing folder within the "pages" folder if you want to add a structure within the module.
. Add the following standard content to your file and modify it accordingly:
+
[source,asciidoc]
----
include::ROOT:attachment${page_template_name}[]
----
