= Creation of standards
:description: Summarizes how standards are created at ASAM.
:keywords: standard,READYFORREVIEW
:level: leveloffset=+1
:sublevel: leveloffset=+2,tag=!related

include::partial$_attributes.adoc[]


This page describes the structure of standards documents and the types of standards that are produced in projects.

== Classification of standards

There are two types of standards: <<Base Standard,Base Standards>> and <<Associated Standard,Associated Standards>>.

Standards can consist of several parts.
These parts are independent (e.g. <<Technology reference,technology references>>) and must each individually comply with the <<Structure of standards,basic document structure for ASAM standards>>.

include::compendium:page$TBD/base_standard.adoc[{sublevel}]

include::compendium:page$TBD/associated_standard.adoc[{sublevel}]

== Set Of Standards
A "**set of standards**" is a special form comprising different elements in one standard.


== Structure of standards
ASAM provides a template for creating an ASAM specification, including a description of use and illustrated by examples.
The style sheet defines an identical look & feel for all ASAM standards.
The main definitions are for the headers and footers, and for the cover page and directories.
Rules for designing graphics, tables, source text, headings, etc. are included.


