= Development Phase Details - Development Cycle
:keywords: development
:description: Development phase details

include::partial$_attributes.adoc[]


== Phase Diagram
The development phase consists of the xref:development/phase_details-setup.adoc[Setup Step], followed by the main development loop (<<fig-development-main-cycle-diagram,Main Cycle>>).
This page covers the Development Cycle and all its sub-steps as well as participating in relevant Controlling Meetings.
Each sub-step is further detailed on its respective page.


[#fig-development-main-cycle-diagram]
image::compendium:asam/development_phase-main.svg[title="The Development phase's main cycle in detail, using the xref:concepts:diagram_notations.adoc[ASAM Project Phase Notation]"]

While the project is actively being developed, it follows the main development cycle of planning, developing, and reviewing.
Occasionally, there are project-independent events happening, such as "Controlling Meetings", where each project may or must participate in.
In particular, there are the __CGSim Controlling Meetings__ (mandatory for all Simulation Domain projects during the Development phase) and the __TSC Controlling Meetings__. +
Typically, projects present their current (i.e. the latest updated) status report to allow the respective panel to monitor and intervene, if necessary.



== Development Phase Timeline
Each project defines their own timeline during the Proposal phase.
Therefore, there is no standard Development phase timeline. +
However, there are typical categories for project length.
These are shown below.

TODO

Additionally, a project may request additional time if the project's content turns out to be more complex than anticipated.
// * 8-12 weeks for creating the draft
// * 1 day of Proposal Workshop (announced 4-6 weeks ahead of time)
// * 1-4 weeks of finalizing the draft and enrollment
// * proposal publication
// * proposal review, presentation, and project decision

// image::compendium:asam/proposal_phase_timeline.drawio.svg[title=Typical Proposal phase timeline]


== Development Phase Steps
The Development phase consists of the following steps, which are explained in detail in their own sections:

* Cycle
** <<Cycle Planning>>
** <<Cycle Development>>
** <<Cycle Review>>
* Controlling Meetings
** <<TSC Controlling Meeting>>
** <<CGSim Controlling Meeting>>


---

=== Cycle Planning
[cols="3,1,10"]
|===
.3+|image:compendium:asam/development_phase-planning.svg[]
>h|Purpose
|To plan the next development cycle on both a high and a low level in form of a milestone

>h|Responsible
|{role-project-lead} + {role-ccb}; +
{role-wg-lead}

>h|Involved
|{role-wg-lead}; +
{role-wg-member}, {role-service-provider}, {role-technical-writer}

|===

NOTE: This is a multi-step task.

TODO +
See xref:development/cycle_planning.adoc[].

---

=== Cycle Development
[cols="3,1,10"]
|===
.3+|image:compendium:asam/development_phase-cycle.svg[]
>h|Purpose
|To develope the content for the planned milestone.

>h|Responsible
|{role-wg-member},
{role-service-provider},
{role-technical-writer}

>h|Involved
|{role-project-lead},
{role-wg-lead}

|===

NOTE: This is a multi-step task.

TODO +
See xref:development/cycle_development.adoc[].

---

=== Cycle Review
[cols="3,1,10"]
|===
.3+|image:compendium:asam/development_phase-review.svg[]
>h|Purpose
|To review the achievements for the planned milestone and to create a project status report.

>h|Responsible
|{role-project-lead} + {role-ccb}; +
{role-wg-lead}

>h|Involved
|{role-wg-lead}; +
{role-wg-member}, {role-service-provider}, {role-technical-writer}

|===

NOTE: This is a multi-step task.

TODO +
See xref:development/cycle_review.adoc[].

---

=== TSC Controlling Meeting
[cols="3,1,10"]
|===
.3+|image:compendium:asam/development_phase-customstep.svg[]
>h|Purpose
|TODO

>h|Responsible
|TODO

>h|Involved
|TODO

|===

TODO +
See xref:development/customstepfile.adoc[].

---

=== CGSim Controlling Meeting
[cols="3,1,10"]
|===
.3+|image:compendium:asam/development_phase-customstep.svg[]
>h|Purpose
|TODO

>h|Responsible
|TODO

>h|Involved
|TODO

|===

TODO +
See xref:development/customstepfile.adoc[].

