= Development Phase Details -- Setup Step
:keywords: development
:description: Development phase details

include::partial$_attributes.adoc[]


== Phase Diagram
The development phase consists of the <<fig-development-setup-step-diagram,Project Setup Step>>, followed by the xref:development/phase_details-cycle.adoc[main development loop].
This page covers the Setup step and all its sub-steps.
Each sub-step is then further detailed on its respective page.

[#fig-development-setup-step-diagram]
image::compendium:asam/development_phase-setup.svg[title="The Development phase's setup step in detail, using the xref:concepts:diagram_notations.adoc[ASAM Project Phase Notation]"]

At the beginning of the Development phase, the project team gets together for a <<Kick-off Workshop>>.
Here, the team decides on key topics of the project and also elects the Project Lead. +
In parallel to that, the {gtm} sets up the repository and the mailing list for the project.
After the workshop has happened, the repository is updated with the outcomes from it.

If the project has requested budget for one or more Service Providers, a call for offer is issued, potential Service Providers present their offers, and the project decides on whom to contract.
After the Service Provider or Providers have been chosen, they receive an onboarding.


== Development Phase Setup Sub-Steps
The Development phase consists of the following steps, which are explained in detail in their own sections:

* <<Prepare Kick-off Workshop>>
* <<Kick-off Workshop>>
* <<Set Up Project Repository>>
* <<Set Up Mailing Lists>>
* <<Update Repository After Kick-off Workshop>>
* <<Engage Service Providers>>


---

=== Prepare Kick-off Workshop
[cols="3,1,10"]
|===
.3+|image:compendium:asam/development_phase-kick-off_preparation.svg[]
>h|Purpose
|To prepare the kick-off workshop for the Development phase.

>h|Responsible
|{role-gtm}

>h|Involved
|{role-wg-member}

|===

Prepare the Kick-off Workshop for the Development phase at least 2 weeks ahead of time. +
See xref:development/kick-off_workshop_preparation.adoc[].

---

=== Kick-off Workshop
[cols="3,1,10"]
|===
.3+|image:compendium:asam/development_phase-kick-off.svg[]
>h|Purpose
|To define all project-specific definitions and elect a Project Lead as well as all WG Leads.

>h|Responsible
|{role-gtm}

>h|Involved
|{role-wg-member} +
-> {role-project-lead} +
-> {role-wg-lead}

|===

This workshop's goal is to define all central aspects, particularly regarding organization and processes, and elect the Project Lead for the project. +
See xref:development/kick-off_workshop.adoc[].

---

=== Set Up Project Repository
[cols="3,1,10"]
|===
.3+|image:compendium:asam/development_phase-repo_setup.svg[]
>h|Purpose
|To set up the repository of the project so that the project members can start working on it.

>h|Responsible
|{role-gtm}

>h|Involved
|{role-wg-member}

|===

In parallel to the workshop preparation and execution, the GTM sets up the project's repository.
This is done using a template repository for new projects or using the previous one for version updates or revisions. +
See xref:development/project_setup.adoc[].

---

=== Set Up Mailing Lists
[cols="3,1,10"]
|===
.3+|image:compendium:asam/development_phase-mailing_list.svg[]
>h|Purpose
|To prepare the project's mailing list.

>h|Responsible
|{role-gtm}

>h|Involved
|{role-wg-member}

|===

The GTM takes the list of enrolled members, creates a new xref:tooling:teams-and-sharepoint.adoc[MS Teams] channel for the project (if it does not exist yet), creates a related Sharepoint folder, and adds all participants to that channel and folder. +
The channel can then also be used as a mailing list.

---

=== Update Repository After Kick-off Workshop
[cols="3,1,10"]
|===
.3+|image:compendium:asam/development_phase-repo_update.svg[]
>h|Purpose
|To incorporate the results from the Kick-off Workshop into the project's repository.

>h|Responsible
|{role-project-lead},
{role-wg-lead},
{role-ccb}

>h|Involved
|{role-gtm}

|===

The Project Lead takes the output from the Kick-off Workshop and incorporates it into the previously setup repository.
In particular, they assign the correct roles and rights and update any descriptions or README related to users and roles. +
To do so, the GTM supports them by granting them the rights to maintain the repository.
Additionally, the GTM may support with technical problems and questions regarding the used remote repository platform.

The following topics need to be updated:

* Milestones
* Create Issues for all known topics
* Assign milestones and labels to issues
* Update timeline in README in repository
* Set up or update CI pipeline, if necessary

After having assigned the correct roles, the Project Lead may delegate specific tasks to the WG Leads and/or the appointed {ccb} members. +
For more information on this step, see the xref:compendium:Guidelines/workflow-trunk.adoc#_initial_setup[Initial Step] of the Trunk-based workflow in the Compendium.

---

=== Engage Service Providers
[cols="3,1,10"]
|===
.3+|image:compendium:asam/development_phase-engage_sp.svg[]
>h|Purpose
|To select and contract one or more Service Providers.

>h|Responsible
|{role-project-lead},
{role-wg-member}

>h|Involved
|{role-gtm},
{role-service-provider}

|===

NOTE: This is a multi-step task.

In case the project requested budget for support through Service Providers, the project must issue a call for offer, review received offers, select one or more Service Providers, and introduce them to the project after the contracts have been signed. +
See xref:development/engage_service_provider.adoc[].

---

