= Decisions and escalations
:description: Contains information on decisions and when to escalate.
:keywords: meeting
:page-layout: progress
:page-progress_bar: progress_bar_simple-decisions_and_escalations.svg

include::tour_guide:partial$_attributes.adoc[]

//tag::body[]

== Decisions in meetings
Participants of a meeting can make decisions on topics within the scope of their respective group.
This means that a subgroup can make decisions on all topics related to their subgroup's task, whereas decisions in a project-level meeting typically concern the project as a whole.

[horizontal]
Project-level:: Can make decisions on all topics that affect the whole project or parts thereof within the defined project scope. +
May prepare suggestions for topics that alter the current scope or affect other projects as well.
These suggestions, however, must be escalated to the appropriate ASAM-level meeting.
Subgroups:: Can make decisions on all topics assigned to this particular subgroup. +
May prepare suggestions for topics that affect other subgroups. 
However, topics that go beyond the subgroup's responsibilities must be escalated to the whole group.


== Escalation of topics
=== From Subgroup to group
A topic must be presented at the next xref:tour_guide:meetings/types.adoc#_project-level_meetings[project-level meeting] when:

* Changes to the underlying data model
* It is requested by the Subgroup
* It is requested by the Project Lead
* It is requested by a project steering committee (e.g. the CCB)
* The subgroup cannot reach a decision on a specific topic or assumes that there are different opinions in the overall project group

The Project Lead may escalate Subgroup decisions to a project level vote.

=== From group to ASAM-level meeting
If a project cannot meet its milestones or budget, it must escalate its status report in the next relevant ASAM-level meeting (such as the TSC controlling meeting).

== Inactive participants
An inactive participant is someone who is registered as an active participant but repeatedly does not partake in meetings or any development activities. 
It is up to the project to decide when a participant is considered inactive.
As an example, a group can decide that three (3) unexcused absences are the limit, with a final warning being issued after the second time. +
Inactive participants can hinder a project by bringing it below the required voting threshold.
They also put more workload on the other active members.
Lastly, inactive participants endanger the project's budget.
It is, therefore, important to identify inactive members quickly and get them to be active again.
As a last resort, inactive (and possibly unresponsive) members can be removed from the project.
This is the responsibility of the responsible lead: Project Lead for project level inactiveness, Subgroup Lead for relevant subgroups.

//end::body[]
