= Decision making
:description: Contains information on decisions and when to escalate.
:keywords: meeting

include::tour_guide:partial$_attributes.adoc[]

//tag::body[]

== Decisions in meetings
This page details the decision making process, escalation path and voting guidelines in ASAM projects.

Development in ASAM projects is collaborative and democratic. Often a decision needs to be made on a technical direction or whether or not a proposed solution is accepted. Some decisions are only possible at specific levels of meeting. 




== Escalation of topics
=== From Subgroup to project group
A topic must be presented at the next xref:tour_guide:meetings/types.adoc#_project_group_meetings[project group meeting] if any of the following apply:

* Changes to the underlying *data model* are involved
* It is requested by one or more *subgroup* participants
* It is requested by the *project lead*
* It is requested by a *project steering committee* (e.g. the xref:tour_guide:meetings/types.adoc#_tsc_meetings[CCB])
* A consensus-based decision is not feasible or possible


=== From project group to TSC meeting
If a project wishes to change its scope or timeline or require a change to budget it submit to the TSC for a decision. Prior to submitting to the TSC, project consensus on the request being submitted is required. See the xref:compendium:Concepts/project_types.adoc#[TSC Guidelines] for guidance on submission. In some cases the TSC may explicitly request presentation of specific material, decisions or of overall project controlling, this shall be communicated clearly beforehand by the OR.


== Guidelines for formal voting

An ASAM Office Responsible will reference these rules prior to the initiation of project votes in any meeting.

Every project member may request that a topic be voted on.
Additionally, the meeting initiator may set up a quick poll first to identify topics that require a formal voting.

== When to conduct voting
Project group voting takes place during meetings. 
Results shall be made available in the corresponding meeting minutes.

By default, a voting is announced in the agenda (before a meeting takes place). 
However, if spontaneous topics arise, ad hoc voting can be held if all impacted participants are present. 
In the case that one or more crucial members for a topic's ad hoc voting are missing, the voting must be postponed and scheduled for the next meeting. 
A voting is only valid if at least 50% of registered active group members cast their vote and the Issue Responsible (if defined) is present. 
An abstention vote counts as a cast vote. 


== Mandatory votings
Some topics require a formal voting.
These typically address project phase changes or things like release decisions. +
The following items must be subjected to mandatory votings:

* Election of Project Lead
* Changes of project scope
* Budget request
* Evaluation of service providers
* Significant changes to deliverables 
* Escalation of topics to TSC
* Release decision

**Note that certain subgroup decisions require an escalation to a project voting. See <<From Subgroup to project group>>.**

== About voting
To be eligible to vote, a member must have been present during the corresponding topic discussion/presentation. 
The only exception to this is voting for topics of static nature, such as meeting frequencies.

In a voting, each member company has one vote, votes cannot be transferred to other companies. 
It is strongly recommended that if a company has multiple participants in a project, they decide on their vote and who will cast it ahead of time. 
If a company casts multiple votes (accidentally or intentionally) and their votes conflict, their vote is counted as abstention.

Choices can be voting-specific (for example if the project is deciding between two or more options). 
Abstention is a valid vote. 
**For approval votes, the choices are yes, no, abstention.**

Voting is decided by simple majority of yes/no votes (abstentions do not count). 
The exception to this rule is a project release vote prior to submission to the ASAM TSC. 
For such a vote a two-thirds majority is needed.

All votes must be cast digitally and through an online tool (so both onsite and remote users can vote). 




//end::body[]
