= Meeting guidelines
:keywords: meeting
:tour_guide_small:

//tag::body[]

include::tour_guide:partial$_attributes.adoc[]

This page describes requirements and guidelines for all project and subgroup meetings.

Clarification or co-development calls as well as similar informal types of meetings may choose to follow these guidelines. Any decisions made in such informal meetings are not valid until reviewed and agreed on in at least a subgroup or project meeting.


== Roles in meetings
[cols="1,1", grid=cols, frame=none]
|===
a|=== Meeting initiator 
a|=== Minute taker


**Every meeting has an initiator.** +
This is the person who calls the meeting.
For project group meetings, the initiator is the project lead by default.
The initiator has the following responsibilities:

* **Before the meeting**
** Ensure a <<Minute taker,minute taker>> is defined.
** Provide the <<Meeting agenda,**agenda**>> for the meeting.
* <<Setting up a meeting,**Set up the meeting**>> and send out the <<Whom to invite,**invites**>> 
* **During the meeting**
** **Moderate** the meeting
** If necessary, **assign tasks** with due dates to participants
* **After the meeting**
* Ensure that **minutes** are shared with participants.

a|The minute taker is designated by the <<Meeting initiator,meeting initiator>>.
This may be the initiator themselves. +

The minute taker has the following responsibilities:

* **Before the meeting**
** Create the xref:tour_guide:meetings/meeting_notes.adoc[meeting minutes] document ahead of time
** Add the provided agenda to the meeting notes
* **During the meeting**
** Document the participants as well as missing meeting members
** Take notes during the meeting
** Document all assigned tasks with their assignees
** Add provided links and documents
* **After the meeting**
** Request missing documents and links from the responsible participants
** Update the notes with delivered updates (e.g. links to files)
** Finalize the notes once everything has been provided
** Inform the initiator in case of overdue tasks
|===

== Best practices 

**Meeting agenda**

A well-structured agenda helps keep meetings organized, efficient, and on track, ensuring that important issues are covered, and goals are achieved within the allocated time.

The <<Meeting initiator,initiator>> of the meeting shall provide a meeting agenda at the latest 1 week in advance of a meeting. 

=== Whom to invite
* The target audience depends on the meeting type.
* While a project is still in the early phase, people will likely be moving from group to group
* For meetings within a group of a project, send the invite to those emails currently registered for the group
* For full project meetings, send the invite to the project's mailing list
* For all meeting types, add the following as CC (if not invited directly):
** The Project Lead and the OR.
** The mailto:openx@asam.net[OpenX Calendar]

NOTE: The list of project participants can be found in the xref:tour_guide:sharepoint.adoc#_participants_list[project's participant list].
This list also contains information on the group or groups each participant is part of.


=== Setting up and running a meeting
// * If you have a Teams license, you can set up a Teams meeting directly in the project's Teams channel.
// See xref:compendium:How-Tos/meetings_in_teams.adoc[].
* All meetings for a project are set up by its OR
* All meetings are hosted using ASAM's Microsoft Teams platform


=== Polls and voting
These are covered in xref:tour_guide:meetings/polls_votes.adoc[].

=== Best practices
* Schedule regular meetings at least every 6-8 weeks
* Send a reminder to all assignees with open topics with enough time ahead of the next meeting
* If you want to give a presentation in a project meeting, upload your presentation in the meeting's "presentations" folder in your project's Sharepoint ahead of time

//end::body[]
