= Meeting guidelines
:keywords: meeting

//tag::body[]

include::tour_guide:partial$_attributes.adoc[]

This page describes requirements and guidelines for all project group and subgroup meetings.

Clarification or co-development calls as well as similar informal types of meetings may choose to follow these guidelines. Any decisions made in such informal meetings are not valid until reviewed and agreed on in at least a subgroup or project meeting.


== Roles in meetings
[cols="1,1", grid=cols, frame=none]
|===
a|=== Meeting initiator 
a|=== Minute taker

a|**Every meeting has an initiator.** +
This is the person who calls the meeting.
For project group meetings, the initiator is the project lead by default.
The initiator has the following responsibilities:

* **Before the meeting**
** Ensure a <<Minute taker,minute taker>> is defined.
** Provide the <<Meeting agenda,**agenda**>> for the meeting.
** <<Setting up a meeting,**Set up the meeting**>> and send out the <<Whom to invite,**invites**>> 
* **During the meeting**
** **Moderate** the meeting
** If necessary, **assign tasks** with due dates to participants
* **After the meeting**
** Ensure that **minutes** are shared with participants.

a|The minute taker is designated by the <<Meeting initiator,meeting initiator>>.
This may be the initiator themselves. +

The minute taker has the following responsibilities:

* **Before the meeting**
** Create the xref:tour_guide:meetings/meeting_notes.adoc[meeting minutes] document ahead of time
** Add the provided agenda to the meeting notes
* **During the meeting**
** Document the participants as well as missing meeting members
** Take notes during the meeting
** Document all assigned tasks with their assignees
** Add provided links and documents
* **After the meeting**
** Request missing documents and links from the responsible participants
** Update the notes with delivered updates (e.g. links to files)
** Finalize the notes once everything has been provided
** Inform the initiator in case of overdue tasks
|===

== Best practices 

**Meeting agenda**

A well-structured agenda helps keep meetings organized, efficient, and on track, ensuring that important issues are covered, and goals are achieved within the allocated time.

The <<Meeting initiator,initiator>> of the meeting shall provide a meeting agenda at the latest 1 week in advance of a meeting. 

=== Whom to invite
* The target audience depends on the meeting type.
* While a project is still in the early phase, people will likely be moving from group to group
* For meetings within a group of a project, send the invite to those emails currently registered for the group
* For full project meetings, send the invite to the project's mailing list
* For all meeting types, add the following as CC (if not invited directly):
** The Project Lead and the OR.

NOTE: The list of project participants can be found in the xref:tour_guide:sharepoint.adoc#_participants_list[project's participant list].
This list also contains information on the group or groups each participant is part of.


=== Setting up and running a meeting
// * If you have a Teams license, you can set up a Teams meeting directly in the project's Teams channel.
// See xref:compendium:How-Tos/meetings_in_teams.adoc[].
* All meetings for a project are set up by its OR
* All meetings are hosted using ASAM's Microsoft Teams platform


=== Polls and voting
These are covered in xref:tour_guide:page$meetings/decisions_and_escalations.adoc##_guidelines_for_formal_voting[].

=== Inactive project member
TODO: For definition of a project member, see PROJECT STUCTURE

An inactive project member is a project member who has been absent, without informing the meeting initiator beforehand, from two consecutive project group and/or subgroup meetings.

Inactive project members make it difficult for a project to accurately gauge its available resources for project planning and may even hinder the decision-making process at project group meetings.

As a first step, inactive project members are contacted by the OR in order to clarify the issue. If no response is received, original commitment is no longer possible or the project member fails to attend a further consecutive meeting, then the project member in question is submitted to the project group for a vote to be removed. 

Removed project members lose access to all project material and meetings.

In the regular controlling presentations to the TSC, the project shall inform the TSC of changes to project members.

Rejoining an ASAM project is subject to the process for <<Joining a running project, joining a running project>>.

=== Joining a running project

An ASAM member may apply at any time to join a running project. +
This is subject to:

* A short presentation to the project by the member on their motivation for joining, their current activities and what they aim to bring to the project
* Formal vote by the project group on whether to accept the request to join

=== Best practices

* Begin discussing document structure early on. This helps to structure discussions. This structure will continue to evolve over the course of the project.

* Identify key terminology early on and define it to ease communication within the project.

* Make use of the advantages of face to face meetings (discussion, fast resolution of items), prepare topics in advance to be addressed in such F2Fs.

* Ensure regular review and reevaluation of project and subgroup status w.r.t. project milestones

* If you have preexisting efforts that you want to contribute to the standard it is possible to transfer IP to ASAM to be used.

* Ensure a project structure that enables resolution finding

* Address meeting participants by name to ensure clear committments and responsibles

* Use examples to demonstrate proposals for resolving features or issues
//end::body[]