= Meeting minutes
:description: Contains all information on meeting notes
:keywords: meeting, meeting_minutes

//tag::body[]

include::tour_guide:partial$_attributes.adoc[]

== Overview

This page outlines ASAM's rules for meeting minutes and how to create them. +

ASAM projects require meeting minutes to be written in one of two tools:
xref:compendium:Tools/remote_repo.adoc[GitLab] (through issues) or Microsoft Word on the project's xref:compendium:Tools/sharepoint.adoc[SharePoint]. +

A template is provided by ASAM in the respective location.

The location of meeting minutes is to be defined by the project during its kickoff. +
For questions please contact the project lead.

The designated xref:tour_guide:meetings/guidelines.adoc#_minute_taker[minute taker] is responsible for taking the notes using this template.

The notes shall document all important decisions (including votes).

== Writing meeting minutes

[tabs]
====
GitLab::
+
--
. Open the GitLab repository of your ASAM standardization project 
. Use the sidebar to open menu:Issues[List]
. Use the button btn:[New issue] to create a new issue
. Use the drop down list to select the meeting notes template menu:Description[Meeting_minutes]
. Follow the instructions that are displayed in the btn:[Write] field
. Add yourself as **Assignee**
. Use the button btn:[Create issue] to publish the meeting notes issue

TIP: You can update the issue after saving.
All changes will be recorded in its history.
--
Sharepoint/Microsoft Word::
+
--
. Open the **SharePoint page** of your ASAM standardization project
. Use the sidebar to open the menu:documents[] folder
. Navigate to menu:02_meeting[]
. Paste a copy of the **Template - Meeting Minutes** file into the folder of your project meeting
. **Fill** the word file with content

TIP: Your file will be saved automatically.
--
====

//end::body[]
