= Meeting minutes
:description: Contains all information on meeting minutes
:keywords: meeting, meeting_minutes
:page-layout: progress // TODO
:page-progress_bar: progress_bar_simple-polls_and_voting.svg // TODO
:tour_guide_small:

//tag::body[]

include::tour_guide:partial$_attributes.adoc[]

== Overview
This page outlines ASAM's rules for meeting minutes and how to create them with issue templates.
Meeting notes (minutes) are to be taken in the project's repository.
The repository contains a template for meeting notes that shall be used.
The designated <<Minute taker, minute taker>> is responsible for taking the notes.

The notes must contain all important decisions (including cast votes).
Additionally, the next scheduled meeting shall be listed here as well.

== How
At ASAM, protocols are written in two main ways.
One is on GitLab and the other is on SharePoint.
Which of the two ways is used in your project you can ask your project lead.

[tabs]
====
GitLab::
+
--
. Open the GitLab repository of your ASAM Standardization project ( menu:Simulation[OpenXXX > OpenXXX Standard] )
. Use the sidebar to open menu:Issues[List]
. Use the button btn:[New issue] to create a new issue
. Use the drop down list to select the meeting minutes template menu:Description[Meeting_minutes]
. Follow the instructions that are displayed in the btn:[Write]-field
. Add yourself as **Assignee**
. Use the button btn:[Create issue] to publish the meeting minutes issue
--
Sharepoint - MS Word::
+
--
. Open the SharePoint page of your ASAM Standardization project
. Use the sidebar to open the documents folder
. Navigate to 02_meeting
. Paste a copy of the **Template - Meeting Minutes**-file into the folder of your project meeting
. Fill the word file with content
. Your file should be saved automatically
--
