= ASAM project polls and voting guidelines
:description: Contains all information on polls and voting
:keywords: poll, vote
:reftext: Polls and voting
:page-layout: progress
:page-progress_bar: progress_bar_simple-polls_and_voting.svg

include::tour_guide:partial$_attributes.adoc[]

== Overview
This page outlines ASAM's rules for voting within ASAM projects. 
Please ensure familiarity with these rules prior to participating in a project poll. 
An ASAM Office Responsible will reference these rules prior to the initiation of project votes in any meeting.

== About polls
Project or Subgroup level polls take place during meetings. 
Their results must be made available in the corresponding meeting notes.

By default, polls are announced in the agenda (before a meeting takes place). 
However, if spontaneous topics arise, ad hoc polls can be held if all impacted participants are present. 
In the case that one or more crucial members for a topic's ad hoc poll are missing, the poll must be postponed and scheduled for the next meeting. 
A poll is only valid if at least 50% of registered active (sub-)group members cast their vote and the Issue Responsible (if defined) is present. 
An abstention vote counts as a cast vote. 
A passive participant (someone not involved in the development directly, such as a spectator or a reviewer) is neither considered for this threshold nor may they participate in any polls.

**Note that substantial changes (e.g., to a data model) being proposed by a subgroup must be presented to and approved by the full project.**

== About voting
To be eligible to vote, a member must have been present during the corresponding topic discussion/presentation. 
The only exception to this is voting for topics of static nature, such as meeting frequencies.
As mentioned above, a passive participant may not vote.

In a poll, each member company has one vote, votes cannot be transferred to other companies. 
It is strongly recommended that if a company has multiple participants in a project, they decide on their vote and who will cast it ahead of time. 
If a company casts multiple votes (accidentally or intentionally) and their votes conflict, their vote is counted as abstention.

Voting choices can be poll-specific (for example if the project is deciding between two or more options). 
Abstention is a valid vote. 
**For approval votes, the choices are yes, no, abstention.**

Voting is decided by simple majority of yes/no votes (abstentions do not count). 
The exception to this rule is a project release vote prior to submission to the ASAM TSC. 
For such a vote a two-thirds majority is needed.

All votes must be cast digitally and through an online tool (so both onsite and remote users can vote). 
You can ask your ASAM Office Responsible for support on creating such a vote ahead of time.