= Meeting types
:description: Definitions for all typical meetings at ASAM.
:keywords: meeting
:page-layout: progress
:page-progress_bar: progress_bar_simple-meeting_types.svg
:tour_guide_small:

//tag::body[]

include::tour_guide:partial$_attributes.adoc[]

== Overview
There are three different types of meetings:

[horizontal]
<<ASAM-level meetings>>:: Coordination within ASAM between multiple projects as well as the with the organization itself
<<Project-level meetings>>:: Coordination for the whole project and general project discussions
<<Subgroup meetings>>:: Coordination within a subgroup of a project

image::compendium:asam/meeting_timeline_example.drawio.svg[title = "Relationship between meeting types"]

== ASAM-level meetings
Each project at ASAM is also part of an overarching project coordination.
This coordination includes different monitoring and steering meetings.
It is the Project Lead's responsibility to represent their project in those meetings.


=== TSC controlling meetings
These are the top level controlling meetings at ASAM, where the https://www.asam.net/active-projects/technical-steering/[TSC^] reviews all current projects.
Here, projects can request more time as well as submit their deliverables for review and, ideally, approval for release.
In case a project faces unforeseen problems and setbacks, these are addressed here. +
Upcoming TSC meetings are announced on the https://www.asam.net/active-projects/technical-steering/[ASAM website^].

=== Information online
If you are interested, the ASAM Website provides some more information on the whole development process.
Check out the https://www.asam.net/active-projects/development-process/[Development Process page^].
If you have additional questions, don't hesitate to contact your ASAM representative.


== Project-level meetings
A project-level meeting is declared as such when all enrolled project members are invited to participate. +
The most common examples for these meetings are

* the Kick-off Workshop
* status meetings
* review meetings

If possible, project-level meetings are to be held face-to-face or as hybrid.
If circumstances forbid this, online meetings are acceptable as well.

ASAM requires projects to hold a project-level meeting at least once a quarter.
The recommendation is to meet every two months. +
A full project meeting is used to hold project level votes, align across Subgroups and evaluate the overall status with respect to the project plan. 


== Subgroup meetings
Every subgroup will schedule their own meetings.
Typically, these meetings happen more frequently than the larger project-level meetings.
Here, the subgroups discuss progress, setbacks, and current topics within their assignment and make related decisions.
Each subgroup shall present results, particularly substantial changes, to the whole project group regularly.

//end::body[]
