= Meeting types
:description: Definitions for all typical meetings at ASAM.
:keywords: meeting

//tag::body[]

include::tour_guide:partial$_attributes.adoc[]

== Overview
An ASAM project may have up to three types of meeting:

[horizontal]
<<TSC meetings,Technical Steering Committtee (TSC) meetings>>:: Coordination within ASAM between multiple projects as well as the with the organization itself
<<Project group meetings>>:: Coordination for the whole project and general project discussions
<<Subgroup meetings>>:: Coordination within a subgroup of a project

image::compendium:asam/meeting_timeline_example.drawio.svg[title = "Relationship between meeting types"]

== TSC meetings
The TSC reviews the status of ongoing projects and approves new activities, budget and releases. Scope changes or unforeseen problems in a project are also subject to approval by the TSC.

All information on upcoming TSC meetings, including date, location and submission deadlines for material is published on the https://www.asam.net/active-projects/technical-steering/[ASAM website^]. 
Meeting minutes are also made available shortly after a meeting. 
Project leads shall be informed of any deadlines by their OR in advance. 
All content for these meetings shall be submitted in advance in accordance with the deadlines set on the website. 

The tasks and processes of the ASAM TSC are documented in the https://www.asam.net/active-projects/resources/#[TSC Guidelines^].


== Project group meetings
A project group meeting is declared as such when all enrolled project members are invited to participate. +
The most common examples for these meetings are

* the kick-off workshop
* status meetings
* review meetings

A project group meeting is used to hold project level votes, align across subgroups and evaluate the overall status with respect to the project plan. 

These meetings are recommended to be held in person (face to face). This must be clearly communicated in the meeting agenda and made available sufficiently in advance to allow for travel organization.

ASAM requires project group meetings to take place at least every 4 months. 
ASAM recommends project group meetings take place at least every two months. 

Formal voting is only possible in a project group meeting. See xref:tour_guide:page$meetings/decisions_and_escalations.adoc





== Subgroup meetings
	

Every subgroup may schedule their own meetings.
Typically, these meetings happen more frequently than the larger project group meetings.
Subgroups discuss progress, setbacks, and current topics within the scope of their assigned work packages.
Each subgroup shall present results, decisions and substantial changes to the whole project group in regular intervals but not less than in quarterly project group meetings.

Decision making in subgroups is consensus-based. Meeting participants engage in open discussions, actively listen to each other's perspectives, and work together to find common ground and solutions that accommodate the interests and concerns of all involved. The goal is to achieve a decision that reflects the broad consensus of the group and ensures that everyone feels heard and valued. No formal voting is supported.

//end::body[]
