= Include code blocks
:description: How-To for including code blocks in ASAM documents (standards).
:keywords: asciidoc,code
:navtitle: [AsciiDoc] Include Code Blocks

include::compendium:partial$_attributes.adoc[]

{asciidoc-icon}

//tag::body[]
This section shows how to include code blocks in an ASAM standard. In the standard case, a fragment direcly from a source code file is included, to not have duplicated code in the document. This is shown in chapter <<Code as fragment from source code file>>.

In some cases, e.g. examples, it is also possible to direcly include code in the documentation. This is shown in chapter <<Code as snippet in document>>.

== Use code fragments from file
[tabs]
====
Source file::
+
--
[[code-tags-in-source-file]]
.Tags for including source code file
[source, js]
----
[...]
// tag::exampleInclude[]  // <1>
function lorem(ipsum, dolor = 1) { // <2>
    const sit = ipsum == null ? 0 : ipsum.sit;
    dolor = sit - amet(dolor);
    return sit ? consectetur(ipsum, 0, dolor < 0 ? 0 : dolor) : [];
}
// end::exampleInclude[] // <3>
[...]
----
<1> Anchor for code block. Reference this anchor using \<<code-example-code-block>>
<2> Caption of the code block
<3> Caption of the code block
--
AsciiDoc::
+
--
....
[[code-example-code-block-tag]]  // <1>
.ASAM example code block using tags // <2>
[source,js]  // <3>
---- // <4>
\include::../resources/examplecode.js[tags=exampleInclude] // <5>
---- // <6>
....
<1> Anchor for code block. Reference this anchor using \<<code-example-code-block-tag>>
<2> Caption of the code block
<3> Sets code highlighting. Possible options: xml, java, ..
<4> Code block delimiter
<5> Directly include source code file with tag marking fragment
<6> Code block delimiter

NOTE: For more information, see the https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/[Asciidoctor reference].
--
Result::
+
--
[[code-example-code-block-tag]]
.ASAM example code block
[source,js]
----
include::compendium:example$/examplecode.js[tags=exampleInclude]
----
--
====

== Code as snippet in document
[tabs]
====
AsciiDoc::
+
--
....
[[code-example-code-block]]  // <1>
.ASAM example code block // <2>
[source,xml]  // <3>
---- // <4>
<ParameterDeclarations> // <5>
  <ParameterDeclaration name="$HostVehicle" parameterType="string" value="car_white"/>
  <ParameterDeclaration name="$TargetVehicle" parameterType="string" value="car_red"/>
  <ParameterDeclaration name="$EgoStartS" parameterType="double" value="50"/>
  <ParameterDeclaration name="$HeadwayTime_LaneChange" parameterType="double" value="0.4"/>
  <ParameterDeclaration name="$HeadwayTime_Brake" parameterType="double" value="1.0"/>
</ParameterDeclarations>
---- // <6>
....
<1> Anchor for code block. Reference this anchor using \<<code-example-code-block>>
<2> Caption of the code block
<3> Sets code highlighting. Possible options: xml, java, ..
<4> Actual Codeblock
<5> Code block delimiter
<6> Code block delimiter
--
Result::
+
--
[[code-example-code-block]]
.ASAM example direct include code block
[source,xml]
----
<ParameterDeclarations>
  <ParameterDeclaration name="$HostVehicle" parameterType="string" value="car_white"/>
  <ParameterDeclaration name="$TargetVehicle" parameterType="string" value="car_red"/>
  <ParameterDeclaration name="$EgoStartS" parameterType="double" value="50"/>
  <ParameterDeclaration name="$HeadwayTime_LaneChange" parameterType="double" value="0.4"/>
  <ParameterDeclaration name="$HeadwayTime_Brake" parameterType="double" value="1.0"/>
</ParameterDeclarations>
----
--
====


== Code & Syntax Highlighting
For inline code, enclose it with ` to apply monospace font.

[tabs]
====
AsciiDoc::
+
--
....
You must set `volume show -is-encrypted true` before it works.
....
--
Result::
+
--
You must set `volume show -is-encrypted true` before it works.
--
====

For code blocks: the html in the square brackets tells the compiler that this is html source code for source highlighting.
[tabs]
====
AsciiDoc::
+
--
....
[source, html]
----
<!DOCTYPE html>
<html>
<body>

<h1>My First Heading</h1>

<p>My first paragraph.</p>

</body>
</html>

----
....
--
Result::
+
--
[source, html]
----
<!DOCTYPE html>
<html>
<body>

<h1>My First Heading</h1>

<p>My first paragraph.</p>

</body>
</html>

----
--
====

//end::body[]