= Merge conflicts: preventing and resolving
:description: Describes how merge conflicts can be resolved with git and how to avoid them ahead of time.
:keywords: git-workflow,merge
:navtitle: [Repository] Merge Conflicts: Preventing And Resolving

include::compendium:partial$_attributes.adoc[]

{repo-icon}

//tag::body[]

//tag::compendium[]
{role-project-participant}
{role-technical-writer}
{role-or}
//end::compendium[]

== Introduction
A merge conflict occurs when multiple different changes (usually made by different users) are to be merged and some or all of the changes contradict each other.
For example, if user A deletes a section in their copy and user B adds a new paragraph to it instead, the merging tool does not know whether to keep the section and add the changes made by user B or to delete it like user A did.


== Avoiding merge conflicts
One way of avoiding merge conflicts is to keep the TTL (time to live) of branches short.
ASAM recommends a TTL of <= 2 weeks. +
If the branch lives longer than expected, merge the parent branch (the trunk or original feature branch) into your branch once in a while.
Alternatively, you can also rebase your branch to the parent branch again.
This way you can solve the conflicts in your branch.

For more information on the differences between merging and rebasing, see https://www.atlassian.com/git/tutorials/merging-vs-rebasing[Merging vs. Rebasing^].


== Resolving merge conflicts
Once you create a merge request, your remote repository will tell you if there are merge conflicts.
It leads you through the conflicting parts and lets you choose if your new or the old content is to be merged.

Another option is to merge locally.
You can use xref:compendium:Tools/git.adoc[] or xref:compendium:Tools/vscode.adoc[] for this.
These tools also provide options to view conflicting changes and help you resolve them.

After you have removed the conflicts, you can create a new commit to your branch that includes the fixes to resolve the conflict in the Merge/Pull Request.
include::compendium:partial$commit_conventions_reminder.adoc[]

For more information, see

[horizontal]
Git:: https://www.atlassian.com/git/tutorials/using-branches/merge-conflicts
GitLab:: https://docs.gitlab.com/ee/user/project/merge_requests/conflicts.html
GitHub:: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

//end::body[]
