= Base Standard
:description: Definition of a base standard.
:keywords: definition,classification,base-standard, READYFORREVIEW

include::compendium:partial$_attributes.adoc[]

{term-icon}

A base standard defines the syntax, abstract models, and functionality for general use.
A base standard is defined in a technology-independent form.
It can use a problem-/task-related notation, e.g., UML for an object model, or any suitable description for protocols.
Typically, a base standard is

* A <<Format Description>> (data structure) **or**
* A <<Protocol Definition>> **or**
* An API

and has the following properties:

* Platform-independent
* Technology-independent
* Supplier-independent
* Does not contradict any other https://www.asam.net/standards/[ASAM standard^]

There are platform- and technology-specific mapping rules for each base standard.
These are defined in a Technology Reference as independent parts of the base standard.

== Format Description

A Format Description standard defines the syntax and semantics of a file format to exchange data.
Currently, these standards are defined in XML, but older standards, such as ASAM MCD-2 MC (ASAP2), still use proprietary ASCII formats.
There are also binary description standards, for example, to store measurement data efficiently.

== Protocol Definition
A Protocol Definition defines the syntax, semantics, and synchronization of communication.
A communications protocol is a system of digital message formats and rules for exchanging the messages in or between computer systems.
A protocol may have a formal description.

== Technology Reference
A Technology Reference specifies the technology-dependent interpretation of the generic standard as mapping rules.
If these mapping rules are complied with, the deliverables are technology-specific implementations of standards that are suitable for a specific implementation platform and native programming languages.
These Technology References are typically available for base standards and companion standards.