
[#sec-tables]
= Tables

This section contains editorial rules on how to create tables:

* <<#sec-ASM-44>>
* <<#sec-ASM-45>>
* <<#sec-ASM-13>>
* <<#sec-ASM-47>>
* <<#sec-ASM-50>>


[#sec-ASM-44]
== Use tables to represent sets of related pieces of information (ASM-44)

Use tables if you have to present a huge amount of similar data in a very compressed form.

*Exceptions*

* If you have only one column in your table, turn the table into a list.

*Example*

```
[#tab-de746de4-8483-4a29-87e1-31cf59244108]
.This is the caption of the table
[%header]
|===
|cell 1_1 | cell 1_2 | cell 1_3
|cell 2_1 | cell 2_2 | cell 2_3
|cell 3_1 | cell 3_2 | cell 3_3
|===
```

*Source*

Microsoft Style Guide: https://docs.microsoft.com/en-us/style-guide/scannable-content/tables


[#sec-ASM-45]
== Use AsciiDoc syntax for tables (ASM-45)

* Indent in AsciiDoc cell content in columns under the table header, if the lines are short enough.
* If the lines are too long, write one cell per line.

*Exceptions*

There are no exceptions.

*Example*

_Code_

```
[#tab-69612353-0fb1-496b-81d6-e42bc07940da]
.This is the caption of the table with short lines
[%header]
|===
|Head 1   |Head 2   |Head 3
|cell 1_1 |cell 1_2 |cell 1_3
|cell 2_1 |cell 2_2 |cell 2_3
|cell 3_1 |cell 3_2 |cell 3_3
|===
```

```
[#tab-4c824f78-b3ce-4d16-a19b-c3732d066917]
.This is the caption of the table with long lines
[%header]
|===
|Head 1 |Head 2 |Head 3
|cell 1_1 with a very long line in the content
|cell 1_2
|cell 1_3

|cell 2_1
|cell 2_2 with a very long line in the content
|cell 2_3

|cell 3_1
|cell 3_2
|cell 3_3 with a very long line in the content
|===
```

_Result_

[#tab-69612353-0fb1-496b-81d6-e42bc07940da]
.This is the caption of the table with short lines
[%header]
|===
|Head 1   | Head 2   | Head 3
|cell 1_1 | cell 1_2 | cell 1_3
|cell 2_1 | cell 2_2 | cell 2_3
|cell 3_1 | cell 3_2 | cell 3_3
|===

[#tab-4c824f78-b3ce-4d16-a19b-c3732d066917]
.This is the caption of the table with long lines
[%header]
|===
|Head 1 |Head 2 |Head 3
|cell 1_1 with a very long line in the content
|cell 1_2
|cell 1_3

|cell 2_1
|cell 2_2 with a very long line in the content
|cell 2_3

|cell 3_1
|cell 3_2
|cell 3_3 with a very long line in the content
|===

*Source*

ASAM Writing Guide: 5.3. Tables

https://docs.asciidoctor.org/asciidoc/latest/tables/build-a-basic-table/


[#sec-ASM-13]
== Create an anchor with an UUID for every table (ASM-13)

The table anchor consists of `[#`, the string `tab-`, a following UUID, and `]`.

*Exceptions*

If you do not know how to use unique IDs, insert `[#tag-uid]` as a placeholder.
The placeholder will trigger a pipeline warning so that the technical writer can help with creating a unique ID.

*Example*

```
[#tab-c1b53e88-ef6e-48c2-9b89-3df8368b50e2]
.This is the caption of the table
[%header]
|===
|cell 1_1 | cell 1_2 | cell 1_3
|cell 2_1 | cell 2_2 | cell 2_3
|cell 3_1 | cell 3_2 | cell 3_3
|===
```

*Source*

ASAM Writing Guide: 5.3. Tables


[#sec-ASM-47]
== Create a caption for every table (ASM-47)

*Exceptions*

There are no exceptions.

*Example*

```
[#tab-c3a7de98-e770-43a1-8c94-6086ca58190d]
.This is the caption of the table
[%header]
|===
|cell 1_1 | cell 1_2 | cell 1_3
|cell 2_1 | cell 2_2 | cell 2_3
|cell 3_1 | cell 3_2 | cell 3_3
|===
```

*Source*

ASAM Writing Guide: 5.3. Tables


[#sec-ASM-50]
== Start text in the table header with a capital letter (ASM-50)

* In a cell in the header row of a table, only the _first word_ begins with an uppercase letter (sentence-style capitalization).

*Exceptions*

_Acronyms_ and _proper names_ are spelled as is.

*Example*

[#tab-ec0debde-c4ab-4ade-b06e-ee74758bef42]
.Use of uppercase in the table header
[%header]
|===
|no                                             |#Yes#
|[.line-through]#Wrong Formatting of a Heading# |Correct formatting of a heading
|[.line-through]#Asam rules to follow#          |ASAM rules to follow
|[.line-through]#Scope of OpenScenario#         |Scope of ASAM OpenSCENARIO
|===

*Source*

Microsoft Style Guide: https://docs.microsoft.com/en-us/style-guide/scannable-content/tables

ASAM Writing Guide: 4.5. Uppercase and lowercase
