= Contribution workflow
:description: Explains the basic contribution workflows.

//tag::body[]

include::tour_guide:partial$_attributes.adoc[]

include::compendium:partial$issue_labels.adoc[]

== Overview 
Developing content for ASAM standards is focused around the concept of xref:tour_guide:contribution/contribute_with_issues.adoc[contributing with issues]. +
The following sections describe this workflow in more detail.


.ASAM contribution workflow
image::tour_guide:workflow/asam_contribution_workflow-StateDiagram.drawio.svg[]

---


[tabs]
====
New::
+
--
[cols="<.<1,<.<3a"]
|===

|What
|A new issue that needs to be classified to a type.

|Who
|<<Workflow Manager>>

|State Label
|{isStateNew-label}

|Transitions 
|
Issue is a duplicate::-> CLOSED ({resolutionTypeDuplicate-label}) +
Type assigned::-> CLASSIFIED
|===

[cols="<.<1,<.<3a"]
|===

|Actions that must be taken prior to state transition
|
* Categorize the issue (i.e. assign the issue type)
** If the issue has been raised previously or was solved in another issue, assign {resolutionTypeDuplicate-label} and close the issue
** Otherwise, assign the correct type (one of):

+
Bug:::
An issue that contains contradictions or errors in the standard. 

NewFeature:::
An issue that adds new features to the project. 

FeatureImprovement::: 
An issue that amends or improves existing features. 

Editorial::: 
An issue that contains general structural and editorial changes for the whole documentation. 

Infrastructure::: 
An issue related to the repository infrastructure such as CI, builds, document toolchain or similar. 

Question:::
General questions about the project, work-flow or anything related to the standard as well as support requests.  

MeetingMinutes::: 
An issue documenting meeting minutes for an ASAM meeting. On starting, a project shall define the location of all meeting minutes for the project. This is either in a project sharepoint or in the issue list. Meeting minutes shall be kept for each official project meeting. 

|===
--
Classified::
+
--
[cols="<.<1,<.<3a"]
|===

|What
|An issue that has a type and that needs to be accepted by the group.

|Who
|Relevant lead (project lead or subgroup lead)

|State label
|{isStateClassified-label}

|Transitions
|
Issue is a duplicate::-> CLOSED ({resolutionTypeDuplicate-label}) +
Issue is rejected::-> CLOSED ({resolutionTypeRejected-label}) +
Issue is accepted::-> ACCEPTED 

|===

[cols="<.<1,<.<3a"]
|===

|Actions that must be taken prior to state transition
|
* Decide whether to address the issue or not
* If the issue is accepted, it is assigned to a release milestone
* If rejected, {resolutionTypeRejected-label} is assigned
* If duplicate, {resolutionTypeDuplicate-label} is assigned
* If accepted, a release milestone is assigned

|===


--
Accepted::
+
--
[cols="<.<1,<.<3a"]
|===

|What
|An issue that has been accepted by the project group, which needs to be assigned to a responsible, given a due date and needs a clear specification of requirements to be fulfilled.

|Who
|Relevant lead (Project Lead or Subgroup Lead)

|State Label
|{isStateAccepted-label}

|Transitions
|
Prioritized::-> IN PROGRESS
|===

[cols="<.<1,<.<3a"]
|===

|Actions that must be taken prior to state transition
|
* Assign the issue to a project participant -> the solution responsible
* Check if the issue needs to be split into multiple sub-issues or tasks (making it a parent issue)
** If it needs to be split, each sub-issue enters state ACCEPTED immediately
** Each sub-issue applies the remaining workflow individually
** A parent issue may only be closed if all its sub-issues have been closed
* Set a <<Due dates,due date>> for the solution (should not exceed 4 weeks of development)
* Clear specification of requirements to be fulfilled by a solution

|===
--
In Progress::
+
--
[cols="<.<1,<.<3a"]
|===

|What
|An issue that is assigned a responsible, has a due date and clear requirements, which now needs to be implemented in a solution.

|Who
|Solution responsible (issue assignee)

|State Label
|{isStateInProgress-label}

|Transitions
|
Solution developed::-> IMPLEMENTED
|===

[cols="<.<1,<.<3a"]
|===

|Actions that must be taken prior to state transition
|
* Develop a solution together with relevant group (solution team, see xref:tour_guide:contribution/issue_implementation.adoc[])
* Document the solution by creating a merge/pull request. Some projects do not yet use the DevOps platforms of ASAM. In this case the solution location is to be agreed on by the project on start.
* Coordinate, monitor and discuss developments within solution team
* On solution completion, set a due date for review (should not exceed 2 weeks)
* Inform project lead and any relevant subgroups of issue review 

|===
--
Implemented::
+
--
[cols="<.<1,<.<3a"]
|===

|What
|An issue that has a solution in an associated merge request or document, which is ready to be reviewed by the group.

|Who
|Workflow manager

|State Label
|{isStateImplemented-label}

|Transitions
| 
Solution accepted::-> REVIEWED +
Solution rejected::-> IN PROGRESS
|===

[cols="<.<1,<.<3a"]
|===

|Actions that must be taken prior to state transition
|
* Perform solution review
** Project group or delegated subgroup reviews solution and documents their feedback:
*** General feedback: as comment on Merge/Pull Request
*** Specific feedback: as review in changes tab
*** If the solution is documented otherwise, the use of comments in the document is recommended
** Identified minor corrections are implemented directly in collaboration between reviewers and solution responsible
* Discuss review results in project group meeting
* Accept or reject solution and document decision in issue
** Identified major corrections lead to rejection of solution
** If accepted, appoint and assign solution to an <<Integrator>> (responsible for integrating the solution) 


|===
--
Reviewed::
+
--
[cols="<.<1,<.<3a"]
|===


|What
|An issue that has a been accepted by the group, has an assigned integrator, which is ready to be integrated into the standard or project.

|Who
|<<Integrator>>

|State Label
|{isStateReviewed-label}

|Transitions
|
Solution implemented::-> INTEGRATED +
Major questions::-> IMPLEMENTED
|===

[cols="<.<1,<.<3a"]
|===

|Actions that must be taken prior to state transition
|
* Refine content and apply ASAM Editorial Guide
* Document any questions in the issue
* Clarify minor questions with solution responsible
* If any major questions arise, change state back to Implemented
* When integrated (and if applicable), remove the "Draft:" flag from the Merge Request
* Assign to the solution responsible of the ticket

|===
--
Integrated::
+
--
[cols="<.<1,<.<3a"]
|===

|What
|An issue that has been integrated, is assigned to the solution responsible, which is ready to be checked and all open comments are resolved.

|Who
|Solution responsible

|State Label
|{isStateIntegrated-label}

|Transitions
|
Integration OK::-> READYFORMERGE +
Integration NOK::-> REVIEWED +
Integration OK::-> CLOSED ({resolutionTypeFixed-label}) Note: This is only applicable for projects that do not use a docs-as-code workflow.
|===

[cols="<.<1,<.<3a"]
|===

|Actions that must be taken prior to state transition
|
* Review the integration
** Is the original content still correctly represented?
** Are all discussions resolved?
* Add feedback as comments
* Add verdict as comment in issue
** If accepted, assign issue to the <<Workflow Manager>>
** If accepted (and if applicable), approve the merge request
|===
--
Ready for Merge::
+
--
[cols="<.<1,<.<3a"]
|===

|What
|An issue that has been integrated and is assigned to the workflow manager, which is ready to be merged.

|Who
|<<Workflow Manager>>

|State Label
|{isStateReadyForMerge-label}


|Transitions
|
Merged::-> CLOSED ({resolutionTypeFixed-label}) +
Merge Conflict::-> INTEGRATED
|===

[cols="<.<1,<.<3a"]
|===

|Actions that must be taken prior to state transition
|**Note that this is only applicable to projects with a docs-as-code workflow**

* Merge the assigned Merge/Pull Request
** If any major merge conflicts arise, these are to be documented and the ticket is reassigned to the Solution Responsible, and change back to the previous state
** If the merge completes successfully, close the Merge/Pull Request and the associated issue(s)


|===
--

====

== Due dates
The due date in issues shall be used to indicate the expected finalization date for the development of the solution.
This date marks the point at which the solution can be reviewed and, ideally, accepted for integration.

ASAM recommends that solution development for issues is scoped to require no more than 4 weeks.
This means that issues where the solution is expected to be more complex should be split into multiple smaller ones, each with an expected resolution time of 4 weeks or less.

If an issue is split into multiple sub-issues, assign due dates for the issue as well as the sub-issues. 
In this case, the due date of the issue itself may exceed the 4 week recommendation.
However, the sub-issues should then stick to that limit.

== Generic roles
The workflow contains some generic roles that each project may implement differently.

=== Workflow Manager
The role "**Workflow Manager**" is an abstract role. 
Each project decides how and whom to assign it to. +
Typical examples are:

* Project Lead
* Office Responsible
* Subgroup leads, if available
* Change Control Board (CCB) representative, if defined

Typically, the Workflow Manager is experienced with using remote repositories.

=== Integrator
The Integrator is responsible for integrating the developed solution into the standard.
Their task is to make sure the writing style is kept consistent and the link:https://internal.pages.asam.net/asam-editorial-guide/editorial-guide-generator/editorialguide-asciidoc/1.0.0/Editorial_guide.html[ASAM editorial rules] are met. 

The Integrator may be a service provider tasked with documentation efforts in the project.
Alternatively, the Integrator may be the Office Responsible or a member of the project group.



//end::body[]
