= Contribution workflow
:description: Explains the basic contribution workflows.
:page-layout: progress
:page-progress_bar: progress_bar_simple-contribution_workflow.svg
:tour_guide_small:

//tag::body[]

include::tour_guide:partial$_attributes.adoc[]

include::compendium:partial$issue_labels.adoc[]

== Overview 
Developing content for ASAM standards is focused around the concept of xref:tour_guide:contribution/contribute_with_issues.adoc[contributing with issues]. +
The following sections describe this workflow in more detail.

.ASAM Contribution Workflow
image::tour_guide:workflow/asam_contribution_workflow-StateDiagram.drawio.svg[]

Each state is described in more detail in the sections below. +
The role listed at the top of each section is the one responsible for it. +
DoR stands for **Definition of Ready**.
It describes the requirements an incoming issue must meet. +
If DoR are specified but not met, the issue is immediately reset to the previous state (including the assignee). +
DoD stands for Definition of Done.
It describes the requirements that must be met for an issue to be allowed to exit this state.
// You may also want to check out ASAM's xref:labels.adoc[**use of labels**].


---

[tabs]
====
New::
+
--
[horizontal]
Who:: <<Workflow Manager>>
State Label:: New
Actions::
* Categorize the issue (i.e. assign the issue type)
** If the issue is a duplicate, assign resolutionType:Duplicate and close the issue
** Otherwise, assign the correct type (one of: Feature, Fix, Documentation)
DoD::
* Issue type assigned OR resolutionType set
Transitions:: 
Issue is a duplicate::: -> CLOSED (resolutionType:Duplicate)
Type assigned::: -> CLASSIFIED
--
Classified::
+
--
[horizontal]
Who:: Relevant lead (Project Lead or Subgroup Lead)
State Label:: Classified
Actions::
* Discuss the issue
* Decide whether to accept it or not
DoR:: 
* Valid type is assigned
* Issue is assigned to relevant lead
DoD::
* Group decision on issue is documented
* If rejected, resolutionType:Rejected is assigned
* If duplicate, resolutionType:Duplicate is assigned
Transitions:: 
Issue is a duplicate::: -> CLOSED (resolutionType:Duplicate)
Issue is rejected::: -> CLOSED (resolutionType:Rejected)
Issue is accepted::: -> ACCEPTED
--
Accepted::
+
--
[horizontal]
Who:: Relevant lead (Project Lead or Subgroup Lead)
State Label:: Accepted
Actions::
* Assign the issue to a group member
* Check if the issue needs to be split into multiple sub-issues (making it a parent issue)
** If it needs to be split, each sub-issue enters state ACCEPTED immediately
** Each sub-issue applies the remaining workflow individually
** A parent issue may only be closed if all its sub-issues have been closed
* Define the issue's priority
* Set a <<Due dates,due date>> for the solution (should not exceed 4 weeks of development)
* Optional: Assign to corresponding milestone
DoR:: 
* Acceptance is documented in issue
DoD::
* Solution developer assigned
* If necessary, split into sub-issues
* Due date set
* Issue requirements specified
Transitions:: 
Prioritized::: -> IN PROGRESS
--
In Progress::
+
--
[horizontal]
Who:: Assignee
State Label:: InProgress
Actions::
* Develop a solution together with relevant group (see xref:tour_guide:contribution/issue_implementation.adoc[])
* Create a Merge/Pull Request 
** In case of strong dependencies to another issue, add the issue number to the request description and the changes to that Merge/Pull Request instead
* Review changes within involved group
DoR:: 
* Solution developer assigned
* Created sub-issues linked, if any
* Due date set
* Issue requirements specified
DoD::
* Requirements in the issue description are met
* All affected artifacts of the standard are covered
* Complete solution included in Merge/Pull Request
Transitions:: 
Solution developed::: -> IMPLEMENTED
--
Implemented::
+
--
[horizontal]
Who:: Project Lead
State Label:: Implemented
Actions::
* Update issue's due date for review (should not exceed 2 weeks)
* Ask project group for review
* Put issue on the next agenda
* Group reviews solution and documents feedback in Merge/Pull Request
** Each reviewer documents their feedback in Merge/Pull Request
*** General feedback: as comment on Merge/Pull Request
*** Specific feedback: as review in changes tab
** Identified minor corrections are implemented directly in collaboration between reviewers and solution developer
* Discuss review results in group meeting
* Accept or reject solution and document decision in issue
** Identified major corrections lead to rejection of solution
** If accepted, appoint an <<Integrator>> (responsible for integrating the solution) and an <<Integration Reviewer>> (responsible for reviewing the integration)
DoR::
* Project Lead assigned
* Relevant Merge/Pull Request linked in issue
DoD::
* Solution reviewed 
* Feedback documented in Merge/Pull Request
* Decision (accepted/rejected) documented
* If accepted: <<Integrator>> assigned
Transitions:: 
Solution accepted::: -> REVIEWED
Solution rejected::: -> IN PROGRESS
--
Reviewed::
+
--
[horizontal]
Who:: <<Integrator>>
State Label:: Reviewed
Actions::
* Refine content and apply ASAM Editorial Guide
* If relevant, apply project-specific writing rules and guidelines
* Document any questions in the issue
* Clarify minor questions with solution developer
* If any major questions arise, change state back to Implemented
DoR::
* <<Integrator>> assigned
DoD::
* Solution completely integrated
* Checked against ASAM Editorial Guide
* Relevant pipelines pass
* All questions documented as comments in issue
Transitions:: 
Solution implemented::: -> INTEGRATED
Major questions::: -> IMPLEMENTED
--


====

== Due dates
The due date in issues shall be used to indicate the expected finalization date for the development of the solution.
This date marks the point at which the solution can be reviewed and, ideally, accepted for integration. +
It is important to note that the development of the solution does not include its implementation!
**Make sure that there is at least 4 weeks of time after the due date to integrate it before any final deadline of the project.**

ASAM recommends that each issues takes no more than 4 weeks to create a solution for it.
This means that issues where the solution is expected to be more complex should be split into multiple smaller ones, each with an expected resolution time of 4 weeks or less.

When scheduling an issue, set its due date according to the issue's estimate. 
If an issue is split into multiple sub-issues, assign due dates for the issue as well as the sub-issues. 
In this case, the due date of the issue itself may exceed the 4 week recommendation.
However, the sub-issues should then stick to that limit.

== Generic roles
The workflow contains some generic roles that each project may implement differently.

=== Workflow Manager
The role "**Workflow Manager**" is an abstract role. 
Each project decides how and whom to assign it to. +
Typical examples are:

* Project Lead
* Office Responsible
* Subgroup leads, if available
* Change Control Board (CCB), if defined

Typically, the Workflow Manager is experienced with using remote repositories.

=== Integrator
The Integrator is responsible for integrating the developed solution into the standard.
Their task is to make sure the writing style is kept consistent and the ASAM editorial rules are met. 

The Integrator may be a service provider tasked with documentation efforts in the project.
Alternatively, the Integrator may be the Office Responsible or a member of the project group.

=== Integration Reviewer
The Integration Reviewer is responsible for reviewing the integrated solution created by the <<Integrator>>. +
They may be an individual or a group. 
Typically, this is also the <<Workflow Manager>>.
In the case that a project has a defined Change Control Board, it shall take on this role.

//end::body[]
