= Hosting workshops
:description: Describes general steps for hosting a workshop.
:keywords: workshop
:navtitle: [Coordination] Hosting Workshops

include::compendium:partial$_attributes.adoc[]

{coordination-icon}


{role-gtm}

To host a workshop is part of the xref:compendium:Guidelines/coordination-meeting_logistics.adoc[].

//tag::body[]
== Face-to-Face Workshop

[cols="1,3"]
|===
h|Duration
| 1 - 2 days

h|Location
| ASAM Event Location
|===

When organizing a face-to-face workshop, a meeting room needs to be reserved depending on the amount of people.
The following options are available at the ASAM office:

[cols="4,3,3"]
|===
|Room           | max Pax without Corona    | max Pax with Corona

|Meeting Room
| 8
| 4

|Pavilion
| 30
| 12

|Audimax
| 60
| 25

|Saal
| 120
| 40
|===

With the duration of at least 1 day, catering is needed as well.
All of this can be organized by the GTM.

== Online workshop

[cols="1,3"]
|===
h|Duration
| 2 - 4 hours

h|Location
| Microsoft Teams
|===

Due to the fact that online meetings are more straining than face-to-face meetings, experience shows that proposal workshops need to be streamlined to reduce the duration to a maximum of 4 hours.

//end::body[]

