= General meeting guidelines
:description: Contains general meeting guidelines for ASAM projects.
:keywords: guideline, meeting
:navtitle: [Coordination] General Meeting Guidelines

include::compendium:partial$_attributes.adoc[]

{coordination-icon}

//tag::body[]
{role-project-lead}
{role-sg-lead}
{role-or}
{role-ccb}

This page contains general guidelines on meetings in projects.
It is intended for meetings during the xref:getting-involved:development_phase.adoc[Development phase], but may be applied to meetings in other phases as well.

//tag::reduced[]
== Meeting host
IMPORTANT: Project meetings are set up by the ASAM office, even when they are not the meeting host.
All other meetings within a project (such as Subgroup meetings) have to be set up by the respective host.

Every meeting has a host.
This is the person who calls the meeting. +
The host has the following responsibilities:

* Define the <<Minute taker,minute taker>>.
They can take that role themselves if they wish.
If not, the assignee has to agree to this task first.
* Provide the <<Meeting agenda,agenda>> for the meeting
* <<Setting up a meeting,Set up the meeting>> and send out the <<Whom to invite,invites>> (exception: project meetings are set up by the ASAM office in coordination with the host)
* Moderate the meeting
* Ensure to stay within the defined timetable
* If necessary, assign tasks with due dates to participants (assignees)
* Ensure that minutes are taken and send out the link to them afterwards
* Follow up with assignees on assigned tasks after the meeting


== Minute taker
The minute taker is designated by the <<Meeting host,meeting host>>.
This may be the host themselves. +
The minute taker has the following responsibilities:

* Before the meeting
** Create the <<Meeting notes,meeting notes>> document ahead of time
** Add the provided agenda to the meeting notes
* During the meeting
** Document the participants as well as missing meeting members
** Take notes during the meeting
** Document all assigned tasks with their assignees
** Add provided links and documents
* After the meeting
** Request missing documents and links from the responsible participants
** Update the notes with delivered updates (e.g. links to files)
** Finalize the notes once everything has been provided
** Inform the host in case of overdue tasks


== Meeting agenda
The <<Meeting host,host>> of the meeting is responsible for providing a meeting agenda ahead of time. +
The agenda must be shared in the invite to the meeting.
The agenda also has to be included in the <<Meeting notes,meeting notes>>.

Each agenda must at least have the following contents:

* https://www.asam.net/active-projects/resources/[Antitrust Reminder^]
* votes on previous minutes
* documentation of participants
* voting template
* agenda items


== Whom to invite
* The target audience depends on your meeting type.
* While a project is still in the early phase, people will likely be moving from group to group
* For meetings within a group of a project, send the invite to those emails currently registered for the group
* For full project meetings, send the invite to the project's mailing list
* For all meeting types, add the following as CC (if not invited directly):
** The Project Lead and the OR.
** The mailto:openx@asam.net[OpenX Calendar]
// ** The mailto:openx@asam.net[OpenX Calendar] (see xref:compendium:Tools/calendar.adoc[shared OpenX Calendar]).
// ** The https://support.microsoft.com/en-us/office/send-an-email-to-a-channel-in-teams-d91db004-d9d7-4a47-82e6-fb1b16dfd51e[Teams channel email^]; this will post the meeting in the channel for all to see.
// See xref:compendium:How-Tos/obtain_channel_email.adoc[].

// NOTE: To find the list of people registered for your group, see the group's Mailing List.
// // Its location is described in the xref:compendium:Guidelines/coordination-teams-channel_file-structure.adoc[Teams&Sharepoint Overview].
// The full project Mailing List is maintained by ASAM, the group's Mailing List is maintained by the respective SG Lead.

NOTE: The list of project participants can be found in the xref:contributing:teams_and_sharepoint.adoc#_participants_list[project's participant list].
This list also contains information on the group or groups each participant is part of.


== Setting up a meeting
// * If you have a Teams license, you can set up a Teams meeting directly in the project's Teams channel.
// See xref:compendium:How-Tos/meetings_in_teams.adoc[].
* Feel free to use whatever solution you or your company normally use.
* If your company does not provide you with a suitable solution, send the details to your ASAM representative and they will assist (either with Teams or Zoom).


== Meeting notes
Meeting notes (minutes) are to be taken in the project's repository.
The repository contains a template for meeting notes that shall be used.
The designated <<Minute taker, minute taker>> is responsible for taking the notes.

The notes must contain all important decisions (including cast votes).
Additionally, the next scheduled meeting shall be listed here as well.


== Best practices
* Schedule regular meetings at least every 6-8 weeks
* Send a reminder to all assignees with open topics with enough time ahead of the next meeting
* Schedule remote meetings only for organizational issues
* Present results, particularly substantial changes in sub-groups, to the whole project group regularly
* If you want to give a presentation in a project meeting, upload your presentation in the meeting's "presentations" folder in your project's Sharepoint ahead of time

//end::reduced[]

== Related topics
* xref:compendium:Guidelines/coordination-hosting_workshops.adoc[].
* xref:compendium:Guidelines/coordination-meeting_moderation.adoc[].
* xref:compendium:Guidelines/coordination-meeting_logistics.adoc[].

//end::body[]