= Tags In Repositories
:description: Describes the tags used in ASAM repositories and their syntax as well as how and when to use them.
:keywords: git-workflow
:navtitle: [Repository] Tags In Repositories

include::compendium:partial$_attributes.adoc[]

//tag::compendium[]
{role-gtm}
{role-project-lead}
{role-ccb}
//end::compendium[]

== What Are Tags?
Tags mark a specific state of a repository in its timeline.
They are most commonly used to demark versions (draft, release candidates, or full releases).

Tags are a feature provided by xref:compendium:Tools/git.adoc[Git].
By extension, they are also available in the xref:compendium:Tools/remote_repo.adoc[remote repositories using Git]. +
Git does not specify any particular syntax.
ASAM and the CI pipelines in the remote repositories, however, require one, depending on the current xref:concepts:project_phases.adoc[project phase].


== When Tags Are Required
A project **MUST** create a tag in the following instances:

* Any time a document has to be shared outside the project, i.e.
** The document of this repository is to be released/published or submitted to TSC
** A review is to be started
* A major milestone has been hit and its progress has to be specifically documented

IMPORTANT: Only tagged (i.e. versioned) documents may be shared officially outside the project group.


== ASAM Tag Syntax
There are two definitions: one for the Proposal Phase and one for the Development Phase (and beyond).
You can find both definitions in the tabulated table below.

[tabs]
====
Proposal Phase::
+
--
[cols=">1,3"]
|===
|Reference
|https://code.asam.net/common/templates/proposal-template/-/tree/main#user-content-tagging-strategy[Proposal Template README^]

|Syntax
|`PYYYY_type` or `PYYYY`

|Description
a|[horizontal]
P::
Mandatory prefix.
YYYY::
The year of the proposal.
type::
The type of release.
Omit the type for the version accepted by TSC.
Otherwise, use one of the following:
dev:::
Start of Proposal writing
ProposalWS:::
Version for Proposal Workshop
TSC:::
Version for TSC submission
Kickoff:::
Version for the Development phase Kickoff Meeting

|Examples
|`P2022_dev` +
`P2023`
|===

--
Development Phase::
+
--
[cols=">1,3"]
|===
|Reference
|https://code.asam.net/common/templates/standard-template/-/tree/main#user-content-tagging-strategy[Standard Template README^]

|Syntax
|`Vx.y.z_type` or `Vx.y.z`

|Description
a|[horizontal]
V::
Mandatory prefix.
x.y.z::
Version number.
x:::
Major version - use for breaking feature changes.
y:::
Minor version - use for backward-compatible feature changes.
z:::
Hotfix version - use for hotfix updates without feature changes.
type::
The type of release.
Omit the type for the release version accepted by TSC.
Otherwise, use one of the following:
prc<N>:::
Pre-release version for ASAM reviews.
<N> indicates which iteration of the pre-release this is (use "1" for the first pre-release version).
rc<N>:::
Release candidate version for public reviews.
<N> indicates which iteration of the release candidate this is (use "1" for the first release candidate).
TSC:::
Version for TSC submission

|Examples
|`V1.0.0_prc3` +
`V1.1.0`
|===
--

====


== Creating Tags
Git::
See https://git-scm.com/book/en/v2/Git-Basics-Tagging

GitLab::
See https://docs.gitlab.com/ee/topics/git/tags.html

GitHub::
GitHub provides this feature under "releases".
See https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository