= Document types of a standard
:description: Summarizes the different document types of a standard at ASAM.
:keywords: standardization
:level: leveloffset=+1
:sublevel: leveloffset=+2,tag=!related

include::partial$_attributes.adoc[]


This page describes the structure of standards documents and the types of standards that are produced in projects.

Standards can consist of several parts.
These parts are independent and must each individually comply with the <<Structure of standards,basic document structure for ASAM standards>>.


== Specification

Each standard contains exactly one Specification.
It defines the syntax, abstract models, and functionality for general use. +
The Specification is defined in a technology-independent form.
It is normative by default.
The document may contain non-normative content as long as it is clearly marked as such.

=== Reference
A standard may contain one or more Reference documents. +
A Reference contains information for implementers of this standard. 
It provides additional information to the <<Specification>> in regards to implementing this standard. +
This information is non-normative.

=== Guideline
A standard may contain one or more Guideline documents. +
A Guideline contains information for users of this standard.
It provides additional information to the <<Specification>> in regards to applying and using this standard, such as specific content examples. +
This information is non-normative.

=== Supplementary material
Sometimes, a project's delivery does not fit either of the above. 
In this case, the project may contain additional, so-called "Supplementary", material.

Note that Supplemental material is only allowed if deemed absolutely necessary and if it is neither <<Specification>>, <<Reference>>, nor <<Guideline>>.

If you are unsure into which category a certain topic falls, you can ask your ASAM Office Responsible.


== Structure of standards
ASAM provides a template for creating an ASAM specification.
It contains all mandatory sections and text blocks.
A style sheet defines an identical look & feel for all ASAM standards.

For new projects, ASAM creates a new document from a template.
Projects for new versions of an existing standard typically build on the previous results.


== Related topics
xref:compendium:Concepts/deliverables.adoc[]
