= Project types
:description: Describes the different project types at ASAM for new members and interested parties.
:keywords: project, type, asam, concept

include::partial$_attributes.adoc[]


WARNING: This section needs approval by TSC.

{project-types-icon}

== Overview
ASAM developes its products and results in projects.
Different result types require different approaches and conditions.
For this reason, ASAM defines four project types, which further characterize the work to be done within the projects. +
They are:

* <<Concept>>
* <<Standard development>>
* <<Study>>
* <<Implementation>>


image::Concepts/project_types_overview.drawio.svg[title="ASAM project types overview", width= 800]

A new project can be triggered by either a new idea, a previous Concept Paper, or a previously released Standard.
The intended output of each project type is a document.

* For a **Concept project**, the output is a Concept Paper (which can be the basis for a follow-up project)
* For a **Standard Development project**, the output is the standard + optional supplemental documents
* For a **Study project**, the output is a Study Report that details the findings of the project.
* For an **Implementation project**, the output is **TODO**.

Note that a new concept project is usually not triggered by a previous one.

// TODO: Project types need to be discussed by TSC first.

== Concept
include::compendium:page$TBD/project-type-concept.adoc[tag=summary]

For more details, see xref:compendium:TBD/project-type-concept.adoc[] in the Compendium.


== Standard development
[tabs]
====
Major version update::
+
--
include::compendium:page$TBD/project-type-standard.adoc[tag=major-summary]
--
Minor version update::
+
--
include::compendium:page$TBD/project-type-standard.adoc[tag=minor-summary]
--
Maintenance::
+
--
include::compendium:page$TBD/project-type-standard.adoc[tag=maintenance-summary]
--
====

include::compendium:page$TBD/project-type-standard.adoc[tag=summary]

For more details, see xref:compendium:TBD/project-type-standard.adoc[] in the Compendium.

== Study
include::compendium:page$TBD/project-type-study.adoc[tag=summary]

For more details, see xref:compendium:TBD/project-type-study.adoc[] in the Compendium.



== Implementation
include::compendium:page$TBD/project-type-implementation.adoc[tag=summary]

For more details, see xref:compendium:TBD/project-type-implementation.adoc[] in the Compendium.



