= Project structure and participant roles 
:description: Links to the current contact page for ASAM Office members.
:keywords: roles, asam, concept

include::partial$_attributes.adoc[]


== Project structure

Project
ASAM standardization activities are always organized in projects. A project is a temporary endeavor undertaken to achieve a particular aim with a definite beginning and a definite end. (aus Handbuch)

A project at ASAM may be anything from a whitepaper, a study group to develop knowledge, a concept to begin defining concepts for a potential standard, or a standardization effort to develop new standards or improve on existing standards.

Project group
Subgroup
CCB
project member
project participant
tsc

== Project roles
OR

PL
SGL
Project participant
TW / (Integrator)
Workflow manager
Solution Responsible
CCB to be defined as subgroup, not as role

== Overview

image::Concepts/roles_overview.drawio.svg[title=Overview over the most relevant roles in ASAM projects.]

It is possible to have more than one role at the same time.
Some roles require you to "enroll" in a project first.
**Enrollment requires an ASAM membership.**


== Role descriptions
The following table contains a list of the most prominent roles at ASAM and a short description for each of them.

include::compendium:partial$roles.adoc[tags=list_of_roles]


// == Further information

// For a complete overview over roles at ASAM, see xref:role-specific:main.adoc[].

// related::role[]
