= Conventions For Images
:description: Contains conventions for creating and using images
:keywords: drawio, image, rules

include::compendium:partial$_attributes.adoc[]

//tag::tools[]
== Tools

ASAM supports the creation of images with xref:tooling:drawio.adoc[Draw.io].
Users can choose to use other tools instead.
The rules described here, however, apply to any image that is to be used in an ASAM document, independent of the tool used to create it.
//end::tools[]

//tag::general[]
== File Formats

Images in ASAM documents shall use one of the following file formats:

* Scalable Vector Graphics ('.svg')
* Draw.io in Scalable Vector Graphics ('.drawio.svg')
* Portable Network Graphics ('.png')


== Naming Image Files

[.underline]#Rules#

* The filename must begin with the `fig-` prefix.
* Add the rest of the filename using lower case letters.
* Use underscore characters to separate words as replacement for spaces (" ").
* Add the appropriate file extension.

[.underline]#Example#

[source, text]
----
fig-this_is_an_example_image.drawio.svg
----


== Colors

Use the ASAM color palet.
The color palet can be found in the Draw.io asset library (https://code.asam.net/common/asam-graphic-library).


== Fonts

If your image contains text, use 'Helvetica' as font in your images.


== Asset Library

Use the provided https://code.asam.net/common/asam-graphic-library[asset library^] to create your images.
If you need a one-time asset, create or add it directly.

If you need a reusable asset that is not contained in the asset library yet, see xref:compendium:tools/drawio/how-to__change_asset_library_content.adoc[].


// == Visual language

// This section contains conventions for visual language, for example using image frames, schades, and objects.


// == Examples

// This section contains examples illustrating the application of the conventions defined in this document.
