= ASAM Deliverables
:description: Summarizes the expected deliverables for ASAM projects.
:keywords: deliverable,standardization
:navtitle: [] ASAM Deliverables


include::compendium:partial$_attributes.adoc[]

{term-icon}

//tag::body[]

The deliverables of a standard package consist of standard documents and other files.
A standard package consists of at least one base standard.
Other deliverable items, as listed on this page, are optional.

== Standard documents
Specification:: The specification contains all normative information such as abstract object models, syntax definitions, and functional behavior descriptions.
It uses a problem- or task-oriented notation, such as UML, BNF, or any suitable description for protocols.
The specification is technology- and implementation-independent.
+
Typically, this is
+
* a format description (data structure) **or**
* a protocol definition **or**
* an API
+
and has the following properties:
+
* Platform-independent
* Technology-independent
* Supplier-independent
* Does not contradict any other https://www.asam.net/standards/[ASAM standard^]
+
Each ASAM standard contains exactly one specification document.
This document is normative by default.
It may contain non-normative content as long as it is clearly marked as such.


Reference::
A reference document contains information related to implementers.
The name of each reference document is prepended by its type or target audience. +
For example, a reference for programmers would be named "Programmers Reference". 
+
This information is non-normative.

Guideline::
A guideline document contains information related to users.
The name of each guideline document is prepended by its type or target audience. +
For example, a guideline for modeling scenarios would be named "Modelling Guideline".
+
This information is non-normative.

== Other files
The following list contains common examples for other types of deliverables.
It is non-exhaustive.

Model files::
Model files typically contain the object model of the standard.
A typical example of a model file in ASAM standards are UML models created with the tool "Enterprise Architect" (.ea).

Schema files::
Schema files define the formal structure and syntax of text files.
They are used for automated schema validation.
Typical examples of schema files are XML definition files (.xsd) or Google protocol buffers definition files (.proto).

Interface definition files::
Interface definition files define programmatic interfaces, such as APIs (Application Programming Interface).
They are used for automatic code generation of the standardized interface for specific programming languages.
A typical example of an interface definition file is the Interface Description Language file (.idl).

Example files::
Example files demonstrate a typical and standard-compliant implementation of the standard.

//end::body[]