= Custom ASAM Antora/Asciidoctor extensions
:description: Lists all custom macros used throughout the Project Guide that require special scripts by ASAM to be processed correctly.
:keywords: macro,extension,antora,asam,custom,project-guide
:page-aliases: special-macros.adoc

include::partial$_attributes.adoc[]


{special-macros-icon}

Antora and Asciidoctor already provide a rich set of features and macros.
However, not all functions that ASAM requires for an efficient and partially automated content structuring are present by default.
For this reason, an Antora extension and an Asciidoctor extension were created.

This page collects all the features of this extension, such as the custom macros, and explains what they do and how to use them.
Each macro also has a detailed instructions page with more details.

TIP: For more information on how to write an Antora extension, see https://docs.antora.org/antora/latest/extend/extensions/[the official extension guide] and check out the relevant https://gitlab.com/antora/antora/-/tree/main/packages[package repositories], particularly their `devdocs` folders.

The source repository of the ASAM extensions is https://code.asam.net/common/asam-antora-extensions.

All following examples assume the extension is located under "./antora_extensions", where "." is the location of the "site.yml" file (the https://docs.antora.org/antora/latest/playbook/[Antora playbook^]).

IMPORTANT: Most extensions are not fully supported in partials, particularly those depending on Asciidoctor features like "include"!


== General configuration
The following table describes general configuration on using the extension:

[cols=">1,3,1,2"]
|===
|Attribute |Description |Default |Example

|id
|Defines an id by which the extension can be specifically called from the CLI.
|none
|`id: asam-extension`

|enabled
|De-/activates this extension by default.
If deactivated, the extension must be explicitely called from the CLI.
Only relevant in combination with `id`.
|true
|`enabled: false`

|require
|Describes the location of the extension.
|none
|`require: './antora_extensions/asam-extension.js'`
|===

.General configuration for ASAM Antora extensions in site.yml
====
[source,yaml]
----
- id: asam-extensions
  require: './antora_extensions/asam-extension.js'
----
====

== Pipeline features
The following sections describe features directly applied through the pipeline. +
These are features that typically are relevant to the whole site.
They enact general rules or features, or they collect information about all content.


[tabs]
====
Orphan pages::
+
--
include::partial$pipeline-orphan_pages.adoc[tag=description]

For more details, see xref:extensions/pipeline-orphan_pages.adoc[].
--
Keyword-overview page::
+
--
include::partial$pipeline-keyword_overview.adoc[tag=description]

For more details, see xref:extensions/pipeline-keyword_overview.adoc[]. +
To see the result of the applied pipeline feature, see
reference::keyword-overview-page[]
--
Page numbering::
+
--
include::partial$pipeline-sequential_sectnums.adoc[tag=description]

For more details, see xref:extensions/pipeline-sequential_sectnums.adoc[].
--
Sequential figure and table numbers::
+
--
include::partial$pipeline-sequential_figs_tables.adoc[tag=description]

For more details, see xref:extensions/pipeline-sequential_figs_tables.adoc[].
--
ISO-2145 style section numbers::
+
--
include::partial$pipeline-iso_style.adoc[tag=description]

For more details, see xref:extensions/pipeline-iso_style.adoc[].
--
Convert local to global page references::
+
--
include::partial$pipeline-global_anchor_replacement.adoc[tag=description]

For more details, see xref:extensions/pipeline-global_anchor_replacement.adoc[].
--
====


== ASAM Antora macros

[tabs]
====
related::
+
--
include::partial$macro-related.adoc[tag="how"]

For more details, see xref:macros/macro-related.adoc[]
--
reference::
+
--
include::partial$macro-reference.adoc[tag=how]

For more details, see xref:macros/macro-reference.adoc[]
--
pages::
+
--
include::partial$macro-pages.adoc[tag=how]

For more details, see xref:macros/macro-pages.adoc[]
--
role_related::
+
--
include::partial$macro-role_related.adoc[tag=how]

For more details, see xref:macros/macro-role_related.adoc[]
--
autonav::
+
--
include::partial$macro-autonav.adoc[tag=how]

For more details, see xref:macros/macro-autonav.adoc[]
--
====

== Source repository
The source code can be found in the https://code.asam.net/common/asam-antora-extensions[ASAM GitLab repository^].


== Including ASAM extensions in a project
. To use the provided ASAM extensions in an ASAM project, add the https://code.asam.net/common/asam-antora-extensions.git[extension repository git^] as submodule to your project.
It is recommended to switch to `master` for the submodule and update regularly to ensure that always the latest version is used!
. Add the <<General configuration,general configuration>> to your project's site.yml, according to where the extensions have been checked out into


== Pages
include::../nav.adoc[tag=asam_extensions]