= Branch Naming Conventions
:description: Contains the conventions for naming branches that ASAM applies.
:keywords: branch, convention

include::compendium:partial$_attributes.adoc[]

== Name Template

====
`[red]#change-type#/[green]#group-name#/[yellow]#branch-title#`
====


== General Guidelines

- Applies to all feature branches
- All lowercase
- Use hyphens instead of spaces


== Change Types
[horizontal]
`feature`:: branches that enhance the standard or add additional features
`fix`:: Bug fixes to contradictions or errors in the standard
`doc`:: Documentation changes only
`experimental`:: (advanced development) Branches where developers want to try out or demonstrate some ideas but don't expect their changes to be integrated directly


== Group Names
The group names are defined by the project.
The table below shows an example.

.Group names for the OSI project
[cols='1,3']
|===
h|Name | Description

|`sm`
| Sensor modeling

|`tp`
| Traffic Participants

|`ha`
| Harmonisation

|`pp`
| Performance & packaging

|`ge`
| Any other, non-group specific developments

|===


== Branch Title
- Should be descriptive and make the change clear, i.e. not "update-sensor-model-x", but rather "initial-radarsensorviewconfig-support"


== Examples

====
    feature/tp/lane-subtype
====
====
    feature/pp/support-for-flatbuffer
====
====
    fix/ge/index-specification-of-trace-files
====