= Development phase meetings
:description: Describes the development phase
:keywords: development, phase, standardization

include::partial$_attributes.adoc[]

== Project-level meetings
ASAM recommends to hold a project-level meeting at least once a quarter.
A full project meeting is used to hold project level votes, align across Sub-groups and evaluate the overall status with respect to the project plan. +
The group can decide to combine these with the Cycle Review meetings since most aspects of a project-level meeting coincides with those of a Cycle Review.
However, if a Cycle takes longer than 3 months, ASAM recommends having a separate project-level meeting in between.


== External ASAM meetings
Each project at ASAM is also part of an overarching project coordination.
This coordination includes different monitoring and steering meetings.
It is the Project Lead's responsibility to represent their project in those meetings. +
Simulation domain projects are required to participate in the following external ASAM meetings:

* <<CGSim controlling meetings>>
* <<TSC controlling meetings>>

image::compendium:asam/development_phase_timeline-cycle_example.svg[title = "Medium length development project example, including cycle details and external ASAM controlling meetings."]


=== CGSim controlling meetings
The Coordination Group Simulation (CGSim) controlling meetings are the default reporting location for development projects.
Here, each project presents their current status regularly (after every cycle).

If a project is behind schedule or faces unpredicted problems and setbacks, or if the project's scope needs to be altered significantly, the project status is escalated at the next <<TSC controlling meetings,TSC controlling meeting>>.
The Project Lead discusses these topics with the project's ASAM Office Responsible to decide whether they need to be escalated to the TSC and, if so, how.


=== TSC controlling meetings
These are the top level controlling meetings at ASAM, where the https://www.asam.net/active-projects/technical-steering/[TSC^] reviews all current projects.
Here, projects can request more time as well as submit their deliverables for review and, ideally, approval for release.
In case a project faces unforeseen problems and setbacks, these are addressed here as well after having been presented at a preceding <<CGSim controoling meetings,CGSim controlling meeting>>.

=== Information online
If you are interested, the ASAM Website provides some more information on the whole development process.
Check out the https://www.asam.net/active-projects/development-process/[Development Process page^].
If you have additional questions, don't hesitate to contact your ASAM representative.

== Escalation of topics
=== From Sub-group to group
Under the following instances must a topic be presented at the next <<Project-level meeting,project-level meeting>>:
* Changes to the underlying data model
* It is requested by the Sub-group
* It is requested by the Project Lead
* It is requested by a project steering committee (e.g. the CCB)
* The Sub-group cannot reach a decision on a specific topic or assumes that there are different opinions in the overall project group

The Project Lead may escalate Sub-group decisions to a project level vote.

=== From group to TSC
If a project cannot meet its milestones or budget, it must escalate its status report in the next CGSim controlling meeting.
See also <<CGSim controlling meetings>> above.

== Inactive participants
An inactive participant is someone who is registered as an active participant but repeatedly and unexcused does not partake in meetings or any development activities. 
How "repeatedly unexcused" absent a participant has to be before being marked as inactive is up to the project to decide.
As an example, a group can decide that three (3) unexcused absences are the limit, with a final warning being issued after the second time. +
Inactive participants can hinder a project by bringing it below the required voting threshold.
They also put more workload on the other active members.
It is, therefore, important to identify inactive members quickly and get them to be active again.
As a last resort, inactive (and possibly unresponsive) members can be removed from the project.
This is the responsibility of the responsible lead: Project Lead for project level inactiveness, Sub-group Lead for relevant sub-groups.

Typically, identification of inactive participants is tied to meeting participation.
The respective Lead must contact members that have been identified as inactive to try and get them involved (again).
If this fails, the inactive member can be removed from the project either through the project controlling or, in difficult cases, through the TSC.
