= Development phase
:description: Describes the development phase
:keywords: development, phase, standardization

include::partial$_attributes.adoc[]


// ====
// [horizontal]
// Involved roles::
// {role-project-participant} --
// {role-wg-lead} --
// {role-project-lead} --
// {role-service-provider} --
// {role-technical-writer} --
// {role-ccb} --
// {role-gtm}

// include::partial$project_phases.adoc[tag=development]
// ====

This page describes how developing a standard works at ASAM.
It describes mandatory, typical, and recommended steps of the Development phase.
Please note that in order for a project to enter this phase, its proposal has to have been approved by the TSC.

== Process overview
// The description of the ASAM standard development process in this section contains all formal process steps to develop an ASAM standard. +
// The process steps are mandatory for the development of new standards and the development of a major version of an existing ASAM standard.
// For all other project types, some of the process steps are optional (see xref:concepts:project_types.adoc[]).

// This process description focuses on the ideal and best-case course of an ASAM project.
// Real projects may have iterations, loops and interventions by the TSC, Office, or Board of Directors. +
// Project groups may decide to re-start a project with an updated project proposal, upgrade to a higher release level, or to prematurely end the project.
// While those events can occur and need to be appropriately managed, they are out-of-scope for this Project Guide.

// image::compendium:asam/development_phase-summary.svg[title="The development phase overview, using the xref:compendium:Guidelines/diagram_notations.adoc[ASAM Project Phase Notation]"]

The process of developing a standard at ASAM starts with a project setup step, which is followed by the development cycle.
The Development phase ends at the date set in the project's milestone plan.
At this point, the project transitions to the next phase, which typically is the Review phase.

image::compendium:asam/development_phase_timeline-development_phase.svg[title = "Examples for a typcial Development phase timeline: short (6 months), medium (12 months), long (18 months)."]

image::compendium:asam/development_phase_timeline-cycle_example.svg[title = "Medium length development project example, including cycle details and external ASAM controlling meetings."]

IMPORTANT: The cycle reviews should be timed such that each of them occurs at least two weeks prior to the respectively next TSC controlling meeting.
This ensures that the Project Lead will have enough time to prepare a status report based on the latest review for these meetings.


== Project setup

[cols="5,^1", grid=cols, frame=none]
|===
a|The initiation of the Development phase is the setup step, particularly the Kick-off Workshop, hosted by ASAM.
Here, the project team is brought up to speed.
The team also defines the project parameters that have not been defined during the Proposal phase.
Lastly, the project team elects a Project Lead who takes responsibility for the project and its coordination with the ASAM office.
The group also defines other roles, such as the members of the Change Control Board (CCB) and the Working Group Leads.
The results from this meeting are then applied to the project's repository, which is set up in the background by ASAM.

Some projects require external help for certain tasks.
In this case (and if the Project Proposal contained a budget for it), the project sends out a request for offers to hire one or more qualified service providers.
The ASAM office will assist with this process.

Once the project is set up, the first development cycle can commence.
At this point, the project has

* an elected project lead
* elected or selected working group leads that are responsible for certain focus points of the project's topics,
* its own project repository (or repositories), complete with README, timeline, and pre-configured pipeline, where all members have been granted access to
* a mailing list with all its members
* a Microsoft Sharepoint structure
* agreed and documented Development phase parameters, such as cycle duration
* agreed and documented project milestones (at least the first two of which have to already be detailed)
* if required: contracts with one or more service providers or, if this process takes longer, ongoing activities for hiring one or more service providers
|image:development_setup_simplified_top.drawio.svg[title=Development project setup]
|===


== Development cycles
[cols="5,^1", grid=cols, frame=none]
|===
a|
This is where the standard is developed.
This part of the Development phase consists of multiple cycles.
Each cycle is structured the same way, with some events occurring only in some of these cycles.
These will be detailed below. +
To learn more about how you can contribute to this phase, check out the pages on xref:contributing:main.adoc[how to start contributing].

ASAM recommends a 2 month interval per Development cycle.
The project team may define a different cycle length, if necessary.
However, it must then also ensure that cycles are then still aligned with external ASAM events, particularly the <<TSC controlling meetings>> and the <<CGSim controlling meetings>>.


=== Cycle Planning
Each development cycle starts with a Cycle Planning.
Here, the Project Lead defines the goals for the cycle together with the members of the CCB and the Working Group Leads.
The decisions are then passed on to the other project members and the service provider(s).
If the project is currently employing a technical writer, they are also informed accordingly.

This is an official meeting hosted by the Project Lead.
Make sure to follow the xref:contributing:meeting_guidelines.adoc[ASAM meeting guidelines].


=== Cycle Development
After the goals for the cycle have been defined, the team contributes to achieving these goals.
Depending on their role, this may be

* creating new issues to initiate discussions and reach decisions on topics
* participating in the discussions within such issues
* creating and uploading reference and additional materials such as images
* transforming agreed issue content into document files (AsciiDoc)

As mentioned above, a standard cycle takes 2 months by default.

Each Working Group may decide to have one or more internal meetings per cycle.
ASAM recommends to have at least one group meeting every second week. +
If so, these are considered official meetings and hosted by the respective Working Group Lead.
Make sure to follow the xref:contributing:meeting_guidelines.adoc[ASAM meeting guidelines].

NOTE: Informal calls and ad hoc meetings between group members are not considered official and do not have to follow the provided guidelines.

=== Cycle Review
At the end of each cycle, the results are reviewed by the team.
Each Working Group presents its results to its Working Group Lead.
Each Working Group Lead then presents their group's status to the other Working Group Leads, the CCB, and the Project Lead.

This will then form the basis for the decisions in the next Cycle Planning.
These reports will also be used to communicate the project's overall progress and status in the <<TSC controlling meetings>> and the <<CGSim Controlling meetings>>.
These meetings are attended by the Project Lead when they occur.
Note that the frequency of these controlling meetings is typically different from that of the Development cycles.
However, the 2 month cycle proposed by ASAM can be easily aligned with both the CGSim and the TSC meetings.

These are official meetings.
Each Working Group Review meeting is hosted by the respective Working Group Lead.
The project's Cycle Review meeting is hosted by the Project Lead.
Make sure to follow the xref:contributing:meeting_guidelines.adoc[ASAM meeting guidelines].


=== Cycle Retrospective
Defining all variables at the beginning of a project that takes months to complete is necessary to get started.
However, experience shows that things change or become more clear with time passing.
This is why ASAM strongly recommends to do a so-called retrospective at the end of each cycle.
It is similar to the Cycle Review, but instead of content it focusses on processes and the development environment.

A retrospective is a meeting where a team reflects their last development cycle (often also referred to as "sprints") and tries to identify the things that really help or hinder the project right now.
The goal is to then take measures to keep the good things and find better solutions or approaches where sinkholes and problems have been identified.
The whole team is encouraged to participate and every voice is to be heard.

The retrospective gives the team a tool to gradually and iteratively improve their processes and workflows.
Ideally, this also pushes motivation in the team and increases the team's cohesion.

If you want to learn more about retrospectives and how they work, there are lots of pages online for the retrospective in Agile processes such as SCRUM. +
Some examples:

* https://backlog.com/blog/three-ways-run-productive-retrospective/
* https://www.scrum.org/resources/what-is-a-sprint-retrospective
* https://www.atlassian.com/team-playbook/plays/retrospective

For input regarding possible activities during these retrospectives, you can turn to this very helpful online tool: https://retromat.org/[window=_blank]

This is an official meeting.
The project may decide whether to have a fixed host or change the assignee/host regularly.
Make sure to follow the xref:contributing:meeting_guidelines.adoc[ASAM meeting guidelines].

|image:development_cycle_simplified_top.drawio.svg[title=Development cycle depiction]
|===


== External ASAM meetings
Each project at ASAM is also part of an overarching project coordination.
This coordination includes different monitoring and steering meetings.
It is the Project Lead's responsibility to represent their project in those meetings. +
Simulation domain projects are required to participate in the following external ASAM meetings:

* <<CGSim controlling meetings>>
* <<TSC controlling meetings>>


=== CGSim controlling meetings
The Coordination Group Simulation (CGSim) controlling meetings are the default reporting location for development projects.
Here, each project presents their current status regularly (after every cycle).

If a project is behind schedule or faces unpredicted problems and setbacks, the project status is escalated at the next <<TSC controlling meetings,TSC controlling meeting>>.


=== TSC controlling meetings
These are the top level controlling meetings at ASAM, where the https://www.asam.net/active-projects/technical-steering/[TSC^] reviews all current projects.
Here, projects can request more time as well as submit their deliverables for review and, ideally, approval for release.
In case a project faces unforeseen problems and setbacks, these are addressed here as well after having been presented at a preceding <<CGSim controoling meetings,CGSim controlling meeting>>.

=== Information online
If you are interested, the ASAM Website provides some more information on the whole development process.
Check out the https://www.asam.net/active-projects/development-process/[Development Process page^].
If you have additional questions, don't hesitate to contact your ASAM representative.

//TODO page on Teams/Sharepoint structure
