= Development Phase
:description: Describes the development phase
:keywords: development, phase

include::partial$_attributes.adoc[]



====
[cols="1,5", frame=none, grid = rows]
|===
h|Involved roles
a| * {role-wg-member}
* {role-wg-lead}
* {role-project-lead}

h| Project phase
| image:compendium:asam/project_lifecycle-development.svg[]

|===
====

// == Getting Started Immediately

// TODO
// [horizontal]
// xref:tooling:working-without-software-installation.adoc#_minimum_required_setup[Minimum Required Setup]:: Check out the minimum required setup to get ready for participation and contribution.

// xref:ideation/enter_new_idea.adoc[]:: Start here to learn how you can enter an idea at ASAM.
// xref:ideation/developing_an_idea.adoc[]:: Start here if you want to further develop an idea you previously entered.
// xref:ideation/raising_interest.adoc[]:: Start here for tips and tricks on finding enough project participants.

== Process Overview
The description of the ASAM standard development process in this section contains all formal process steps to develop an ASAM standard. +
The process steps are mandatory for the development of new standards and the development of a major version of an existing ASAM standard.
For all other project types, some of the process steps are optional (see xref:concepts:project_types.adoc[]).

This process description focuses on the ideal and best-case course of an ASAM project.
Real projects may have iterations, loops and interventions by the __{tsc}__, Office, or Board of Directors. +
Project groups may decide to re-start a project with an updated project proposal, upgrade to a higher release level, or to prematurely end the project.
While those events can occur and need to be appropriately managed, they are out-of-scope for this Project Guide.

image::compendium:asam/development_phase-summary.svg[title="The development phase overview, using the xref:concepts:diagram_notations.adoc[ASAM Project Phase Notation]"]




TODO