= Proposal Phase
:description: Describes the Proposal phase in the ASAM development process for standards.
:keywords: proposal,phase,standard,process,proposal-workshop

include::partial$_attributes.adoc[]

====
[horizontal]
Involved roles::
{role-idea-giver} --
{role-standard-user} --
{role-gtm} --
{role-tsc-member} --
{role-member} --
({role-proposal-submitter})
====

== Process Overview
The purpose of the proposal phase is to transfer xref:ideation_phase.adoc[ideas for a standard development project] into an ASAM project proposal and to obtain a decision on it.

In this phase, the idea is further analyzed, central requirements are formulated, the expected effort quantified, and the timeline defined.
In addition to that, interested parties can sign up during this phase for project participation. +
The proposal is released to attract more attention as well as for transparency.
It is then submitted and presented to the TSC for approval.
If the approval is not given, the proposal can be improved and updated before presenting it again, or the project is dropped by the Idea Giver. +
If the Project Proposal is approved, it transitions to the xref:development_phase.adoc[Standard Development phase].

image::compendium:asam/proposal_phase_v2-simplified.svg[title="The simplified Proposal phase"]

The phase is explained in more detail on the xref:proposal/phase_details.adoc[next page].
If you want to learn more about how to participate in this phase, check out the pages in this chapter or follow the links in the relevant section on this page.

