= Proposal Phase
:description: Describes the Proposal phase in the ASAM development process for standards.
:keywords: proposal,phase,standard,process,proposal-workshop

include::partial$_attributes.adoc[]



// == Getting Started Immediately

// [horizontal]
// xref:proposal/proposal_workshop_preparation.adoc[]:: Start here to learn how you prepare a Proposal Workshop.
// xref:proposal/join_proposal_workshop.adoc[]:: Start here to learn how to join a scheduled Proposal Workshop.
// xref:proposal/proposal_writing.adoc[]:: Start here to learn how to contribute as a participant of a project Proposal.
// xref:proposal/submit_candidacy.adoc[]:: Start here to learn how you can submit a candidacy for Project Lead.
// xref:proposal/submit_proposal.adoc[]:: Start here to learn what to do in order to submit a project Proposal for review by the __{tsc}__.
// xref:tooling:working-without-software-installation.adoc#_minimum_required_setup[Minimum Required Setup]:: Check out the minimum required setup to get ready for participation and contribution.


== Process Overview
The purpose of the proposal phase is to transfer xref:ideation_phase.adoc[ideas for a standard development project] into an ASAM project proposal and to obtain a decision on it.

In this phase, the idea is further analyzed, central requirements are formulated, the expected effort quantified, and the timeline defined.
In addition to that, interested parties can sign up during this phase for project participation. +
The proposal is released to attract more attention as well as for transparency.
It is then submitted and presented to the {tsc} for approval.
If the approval is not given, the proposal can be improved and updated before presenting it again, or the project is dropped by the Idea Giver. +
If the Project Proposal is approved, it transitions to the xref:development_phase.adoc[Standard Development phase].

image::compendium:asam/proposal_phase_v2-simplified.svg[title="The simplified Proposal phase"]

The phase is explained in more detail on the xref:proposal/phase_details.adoc[next page].
If you want to learn more about how to participate in this phase, check out the pages in this chapter or follow the links in the relevant section on this page.

====
[cols="1,5", frame=none, grid = rows]
|===
h|Involved roles
a| * {role-idea-giver}
* {role-standard-user}
* {role-gtm}
* {role-tsc-member}
* {role-member}
* ({role-proposal-submitter})

h| Project phase
| image:compendium:asam/project_lifecycle-proposal.svg[]

|===
====

