= The Release phase
:description: Describes the Release phase in the ASAM development process for standards.
:keywords: release,phase,standard,process, TODO

include::partial$_attributes.adoc[]


====
[cols="1,5", frame=none, grid = rows]
|===
h|Involved roles
a| * {role-project-lead}
* {role-wg-member}
* {role-wg-lead}
* {role-gtm}
* {role-tsc-member}

h| Project phase
| image:compendium:asam/project_lifecycle-release.svg[]

|===
====

== Getting Started Immediately

TODO
// [horizontal]
// xref:proposal/proposal_workshop_preparation.adoc[]:: Start here to learn how you prepare a Proposal Workshop.


== Process Overview
The purpose of the Release phase is to obtain a release decision at ASAM and to publish the new standard.

image::asam-development-process-Release.svg[title="The Release Phase (simplified)",opts=interactive]


== Release Phase Timeline
TODO

== Release Phase Steps
The Release phase consists of the following steps, which are explained in detail in their own sections:

* <<Candidate Release>>
* <<Release Candidate Review>>
* <<Release Decision>>
* <<Publication Preparation>>
* <<Publication>>


=== Candidate Release
[cols="1h,20"]
|===
|Purpose
|To decide upon technical readiness of the standard and submit the deliverables to the TSC.

|Responsible
|{role-project-lead},
{role-wg-member},
{role-wg-lead}
|===

The project group prepares a release candidate and agrees per formal voting to submit the candidate to the TSC for release decision.
Each company has one vote.
The release candidate is accepted by absolute two-thirds majority.
The group's decision is documented in the meeting minutes.

The Project Leader submits the following deliverables to ASAM:

* the standard with all supplemental documents, files and examples that constitute the deliverables to members.
* sources required to generate the deliverables, including written instructions how to generate them.
* revision history documentation (not needed for version 1.0.0).
* new release presentation.

Sources are those digital work products, which can be modified or edited with standard tools such as text editors, image processors or modeling tools, and which are the input for generators that produce the final deliverables.


=== Release Candidate Review
[cols="1h,20"]
|===
|Purpose
|To review the deliverables, to clarify open questions, and to come to an individual conclusion about the release-worthiness of the release candidate.

|Responsible
|{role-tsc-member}

|Involved
|{role-gtm}
|===

The TSC members review the release with special focus on the changes.
They shall clarify open question with the Project Leader prior to the TSC meeting.
TSC members shall make up their mind whether the release candidate is ready for publication.

The minimum review period for release candidates is four weeks.


=== Release Decision
[cols="1h,20"]
|===
|Purpose
|To approve or reject the release candidate.

|Responsible
|{role-tsc-member}

|Involved
|{role-project-lead},
{role-wg-member},
{role-wg-lead}
|===

Decisions on release candidates are put on the agenda of the next available TSC meeting.
Release candidate decisions are handled during the meeting via a three-step process:

. Project leader presents the release candidate to the TSC members.
. TSC members are given the opportunity to ask questions.
. TSC members discuss the proposal (without Project Leader's presence) and then proceed with casting their votes on the release.

The TSC does not modify the content of the release candidate.
If this is deemed to be necessary, then the release shall be rejected.

The voting is carried out in accordance with the TSC voting rules.
The Board Representative for the TSC has to confirm the TSC decision.

The TSC may add requirements for rework of the release candidate and make the release contingent upon the completion of the required rework.
The Office shall check the reworked release candidate submission.
If the required rework has been implemented as defined by the TSC, then the release is effective and the release process continues.


=== Publication Preparation
[cols="1h,20"]
|===
|Purpose
|To prepare all marketing and distribution activities for the new standard release.

|Responsible
|{role-gtm}

|Involved
|{role-project-lead},
{role-wg-member},
{role-wg-lead}
|===

The Office prepares new and updates existing marketing and training material for the new release.
The Project Leader shall support this activity by contributing technical content and reviewing the new or updated marketing and training material, upon request.

The publication of a new standard shall occur within 5 weeks after the effective release.
The publication of a new version of an existing standard shall occur within 3 weeks after the effective release decision.


=== Publication
[cols="1h,20"]
|===
|Purpose
|To go live with the released standard.

|Responsible
|{role-gtm}

|===

The Office carries out all planed publication activities.
As a minimum, the Office undertakes the following publication measures:

* The standard can be sold or published freely and is downloadable from the https://www.asam.net/standards/[ASAM website^].
* The release is announced via newsletter.
* [__Standard Development Only__] New standards and major version releases get a news article on the https://www.asam.net/news-media/news/[ASAM website^].


related::release[]