= Review phase
:description: Describes the Review phase in the ASAM development process for standards.
:keywords: review,phase,standardization,process

include::partial$_attributes.adoc[]


====
[horizontal]
Involved roles::
{role-standard-user} --
{role-member} --
{role-project-participant} --
{role-sg-lead} --
{role-project-lead} --
{role-or}


include::partial$project_phases.adoc[tag=review]
====

== Overview
The purpose of the Review phase is to gather feedback and review the created document(s) by people outside the project group.
The goal is to increase the overall quality and acceptance of the standard prior to its release.

TIP: The project group can (and should!) review their changes regularly during development.
The Review phase is a dedicated "final" review phase before publication.

image::compendium:asam/review_phase.drawio.svg[title="The Review phase"]


== Prerequisites and general requirements
* All deliverables of the standard shall be feature-complete, i.e. the specification or revision of all features of the standard has been finished.
* A partial review of a deliverable (where the deliverable is incomplete) is prohibited!
* The project group members determine whether the standard is ready for the review phase.


== Project group review
[cols="1h,20"]
|===
|Purpose
|To obtain technical review feedback from the project group.

|Responsible
|Project group

|Involved
|Project group
|===

The Project Lead initiates the internal review process.
The Project Group reviews the deliverables and provides feedback.

The default review period for outside reviews is 3 weeks. +

If a project groups has reasons to skip the project group review entirely, it must get approval from the ASAM Office Responsible, the Project Lead, and the ASAM CTO first.

== Group feedback processing
[cols="1h,20"]
|===
|Purpose
|To review and decide upon the reviewers' feedback and to incorporate corresponding changes to the draft standard.

|Responsible
|Project group

|Involved
|Members
|===

The project group has the obligation to review each review feedback and make a decision on how to further work on it.
The decision includes as a minimum the status "accepted", "rejected" or "deferred".
The decision must be documented.

Accepted feedback shall be implemented.
The project group has full authority how to implement the reviewers' feedback into the standard.
They can implement changes as proposed by the reviewer, or decide for a different implementation.

If a reviewer's feedback is actually out-of-scope, since it contains a request to consider a new use-case, feature or requirement, then the feedback shall be rejected and transferred to the ASAM CR-system with status "new".

The project group members have the obligation to review each comment and make a decision.
The project group has full authority to decide, how to handle a comment, e.g. to accept, modify, defer or reject comments, and to make corresponding changes to the standard at their own discretion.

The default feedback implementation period for group reviews is 2 weeks.
If no major setbacks have been identified, the outside review is started.
Otherwise, the project will do another group review.


== Draft release
[cols="1h,20"]
|===
|Purpose
|To create a preliminary version of the standard for carrying out an outside review.

|Responsible
|Project Lead

|Involved
|Office
|===

The Project Lead is responsible for delivering the draft document(s) in a format which is usable in the ASAM IT infrastructure for document reviews.
Changes to the prior version shall be marked in the draft documents or documented in a separate changelog, with clear references to the draft documents.

The Office publishes the start of the outside review process via newsletter and https://www.asam.net/active-projects/public-review/[ASAM website], and provides additional information, such as a brief description of the changes in the standard, review process steps and the review deadline.


Outside reviews are mandatory for development projects of major versions. +
The project group releases a draft of the standard, which is feature-complete and has undergone an internal review.



IMPORTANT: A review of an incomplete set of deliverables is not allowed by default.
The ASAM Office Responsible and the ASAM CTO can make an exception for a project upon request by the Project Lead.
This exception must be provided in written form.
However, each of the provided deliverables still has to be feature-complete.


== Outside review of draft
[cols="1h,20"]
|===
|Purpose
|To obtain technical review feedback from members.

|Responsible
|Members

|Involved
|Office Responsible, project group
|===


The Office provides an IT solution for carrying out the outside review of the draft.
The Office provides technical support for reviewers and ensures that review feedback is accessible to the project group members in a timely manner.

There are two types of outside reviews:
* ASAM member reviews (default)
* Public reviews

ASAM member reviews are the default type of outside reviews at ASAM. +
In general, every ASAM member can download the draft standard and participate in the review.
The Office may restrict the group of reviewers in agreement with the project group members or as per TSC decision.

In a public review, the draft standard is made publicly available without the requirement of being an ASAM member.

IMPORTANT: Only standards that are not going to be sold by ASAM are eligible for a public review with non-members.

Members of the project group are available to answer technical questions from reviewers.

Reviewers should not submit new use-cases, features, or requirements as part of their review feedback.
The Office asks the reviewers to submit such requests via the regular ASAM CR system.
Any incorrectly submitted change requests of this sort can be dismissed or added to a backlog for future versions by the project group.

The default review period for outside reviews is 3 weeks.


== Feedback deadline
[cols="1h,20"]
|===
|Purpose
|To end the public review and have all feedback ready for the next process step.

|Responsible
|Office

|Involved
|none
|===

The Office terminates the outside review of the draft process by:

- removing the draft standard download from the https://www.asam.net/active-projects/public-review/[ASAM website^].
- closing the IT-solution to accept further review feedback.

Once the review period is over, the ASAM office removes the draft standard from public access and makes the review comments available to the project group.


== Outside feedback processing
[cols="1h,20"]
|===
|Purpose
|To review and decide upon the reviewers' feedback and to incorporate corresponding changes to the draft standard.

|Responsible
|Project group

|Involved
|Members
|===

The rules for the processing of outside feedback is identical to the <<Group feedback processing>>, with the following addition:

ASAM has the obligation to inform reviewers about the status of their review feedback, upon their request.

related::review[]

