= Setting up your repository account
:description: How to setup your ASAM account.
:keywords: setup,gitlab, github,account

//tag::body[]

include::compendium:partial$_attributes.adoc[]
include::contributing:partial$_attributes.adoc[]


//tag::icon[]
{remote-icon-page}
//end::icon[]

== Introduction
{remote-xref}[Remote Repositories] provide an integrated working environment and text editor.
With these, users can directly create and edit files without having to install tools like xref:compendium:Tools/git.adoc[] or xref:compendium:Tools/vscode.adoc[]. +
The choice of remote repository depends on the project.
Most ASAM projects use https://code.asam.net/[ASAM's GitLab instance^].
Alternatively, ASAM also supports projects on https://github.com/asam-ev[GitHub^]. +
If you are unsure which type of remote repository your project is using, ask your ASAM Global Technology Manager (GTM).

ASAM recommends looking up specific questions on these platforms and their features in general on their respective online documentation.
Topics related to ASAM rules in projects (e.g. for using issue templates) can be found in the {remote-xref}[Remote Repositories Info Page].

Before you can get started, you need to create and set up an account for the project's online repository.
Select and follow the respective instructions in the tab view below.

include::contributing:partial$icon_reminder.adoc[tag=online-access]

== Setup steps

[tabs]
====
GitLab::
+
--
[cols="^1,8", frame=none, grid=none]
|===
|{gitlab-icon-norole} +
{gitlab-url}[ASAM GitLab^]
a|include::compendium:page$How-Tos/gitlab-setup.adoc[tag=body]
|===
--
GitHub::
+
--
[cols="^1,8", frame=none, grid=none]
|===
|{github-icon-norole} +
{github-url}[ASAM e.V. on GitHub^]
a|include::compendium:page$How-Tos/github-setup.adoc[tag=body]
|===
--
====

//end::body[]