= Documentation As Code
:description: Gives an introduction for the concept of documentation-as-code.
:keywords: concept

include::partial$_attributes.adoc[]
include::{abb}[]

== Introduction
Many newer projects at ASAM follow the concept of Documentation as Code (Doc-as-Code). +
This concept refers to using the same tools and methods for documentation (or standardization) as for writing (software) code.
The main benefit of this concept is the separation of content and text in documents from its layout rules and publishing.

[IMPORTANT]
====
NOT to be confused with the Dog-as-Code concept!!!
----
           __
  \ ______/ V`-,
   }        /~~
  /_)^ --,r'
 |b      |b
----
====

== Concept
As described, the general concept is to use established tools and processes from software development and apply them in the creation of documents.

=== AsciiDoc
At ASAM, the central aspect of this concept is the usage of https://en.wikipedia.org/wiki/Plain_text[plain text^] documents with a https://en.wikipedia.org/wiki/Markup_language[semantic markup language^] in creating standards and other documents, particularly the free https://asciidoc-py.github.io/index.html[AsciiDoc format^].
Its main benefit is the separation of content from style and layout rules, making it possible to specify general layout settings in a separate set of files and instructions for consistency over multiple projects.
Writers also get the benefit of being able to focus on content first, handing of the layouting to other people.

Another benefit is that AsciiDoc files can be opened and edited with any type of text editor, making it a platform-agnostic format.
Different people can write content independent of the operating system on their work devices or requiring specific software licenses.

Finally, the content is decoupled from the target output, making it easy to generate different types of documentation from the same source files, such as single-file PDFs as well as multi-page online documentation in html.
It is even possible to generate multiple types of output in the same process.

TIP: If you want to learn more about AsciiDoc and how to use its powers in writing technical documents, see the official https://docs.asciidoctor.org/asciidoc/latest/[**AsciiDoc Language Documentation**^].

=== Versioning And Repositories
Besides the separation of source text and publication files, using tool-supported document versioning is another main aspect in the Doc-as-Code.
ASAM projects employing Doc-as-Code use the software https://git-scm.com/[Git^] for this purpose. +
It allows for working on different parts, features, or versions of a project separately whilst also providing the necessary features for merging all changes that were made on these different versions again later.
As this works best with plain text documents, it goes extremely well together with the plain text markup approach to document writing explained above.

Content is stored in so-called repositories.
These repositories also contain some files with information about the history and current state of the content.
These repository information is updated and used by Git and usually needs not to be changed by users manually.

TIP: If you want to learn more about Git itself, ASAM recommends online introductions and tutorials such as https://rogerdudler.github.io/git-guide/[this one^].
Additionally, you can find more information on using Git at ASAM in the xref:tooling:git.adoc[tooling section^].


=== GitLab and GitHub
The work on standards is of collaborative nature.
Online repository platforms like GitLab and GitHub support this by providing features for commenting and reviewing content changes as well as issue boards for creating and tracking topics. +
Each project decides independently of each other on which platform it will use.

ASAM employs this concept in the following ways:

// * using <<Issue Tracking,issue tracking>>
// * having a <<Version Control System, version control system>> (e.g. Git)
// * using <<Plain Text Markup,plain text markup>> for content (e.g. AsciiDoc)
// * doing <<Reviews,(code) reviews>>
// * <<Process Automation,automating >>steps in the (code/content) generation.


* Standards are created as plain text
*


Different projects may use different tools or versions of the same tools, but the central ideas stay the same.

== Issue Tracking
Issues are open topics and found bugs collected in a central system. +
ASAM uses xref:tooling:gitlab.adoc[] (self-hosted) and xref:tooling:github.adoc[] (cloud) for different projects.

== Version Control System
A version control system keeps track of changes in a file system. +
ASAM uses xref:tooling:git.adoc[] and some remote solution (either xref:tooling:gitlab.adoc[] or xref:tooling:github.adoc[]).

== Plain Text Markup
A plain text markup language that separates the writing from the publishing.
This means that the content (the "writing") and its styling and layout (the "publishing") are not defined simultaneously (like in Microsoft Word) but applied through specified rules.
Typical examples are the languages Markdown, LaTeX, and AsciiDoc. +
ASAM uses https://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc^] for its documents.

== Reviews
TODO

== Process Automation
ASAM projects typically automate the following steps:

* Convert AsciiDoc files to html and pdf using https://asciidoctor.org/[Asciidoctor^]
* https://en.wikipedia.org/wiki/Lint_(software)[Linting^] and testing documents for rules defined in the xref:compendium:writing_guidelines/editorial_guide.adoc[] and returning found errors
* Publishing results as pipeline artifacts for downloads or distribution
* Running project-specific scripts for additional features, such as converting uml diagrams to AsciiDoc files


For more information on the standard ASAM pipeline, see xref:pipeline_details.adoc[].