= Concepts
:description: Contains a short introduction to all important concepts and terms used throughout the Project Guide.
:keywords: concepts, landing_page

include::partial$_attributes.adoc[]
include::{abb}[]
include::ROOT:partial$_attributes.adoc[]

{getting-started-icon}


include::partial$module-description.adoc[]

== Content

include::../nav.adoc[lines=3..-1]

This part explains the following concepts that are used at ASAM:

Project Types::
ASAM distinguishes multiple types of projects.
Each project type is defined in the respective Proposal phase (see below) and specifies the expected outcome and requirements as well as restrictions for the project.

Project Phases::
A typical project goes through multiple phases at ASAM.
Each phase has specific steps and events that must or can happen. +
Both the phases and the types are illustrated in a fictitious project's lifecycle.

Roles::
There are different roles for people working at or with ASAM.
A person can have one or more roles, and most roles only apply within a given project.

Diagram notations::
This Project Guide uses a BPMN-variant notation for normative Project Phase diagrams.
The general notation is explained with an example.

Doc-as-Code::
The central concept throughout the Project Guide is the concept of Documentation-as-Code (or Doc-as-Code).
It is explained in the context of ASAM standard development.
Child pages then detail some aspects of the concept.

