= Project Types
:description: Describes the different project types at ASAM for new members and interested parties.
:keywords: projects, type, asam, concept

include::partial$_attributes.adoc[]


WARNING: This section needs approval by {tsc}.

{project-types-icon}

== Overview
__{asam}__ developes its products and results in projects.
Different result types require different approaches and conditions.
For this reason, ASAM defines three project types, which further characterize the work to be done within the projects. +
They are:

* <<Concept>>
* <<Standard Development>>
* <<Study>>


image::project_types_overview.drawio.svg[title="ASAM project types overview", width= 800]

A new project can be triggered by either a new idea, a previous Concept Paper, or a previously released Standard.
The intended output of each project type is a document.

* For a **Concept project**, the output is a Concept Paper (which can be the basis for a follow-up project)
* For a **Standard Development project**, the output is the standard + optional supplemental documents
* For a **Study project**, the output is a Study Report that details the findings of the project.

Note that a new concept project is usually not triggered by a previous one.

// TBD: Implementation Project still valid?
// TODO: Update image
// TBD: Implementers forum relevant?
// Project types need to be discussed by TSC first.


== Concept
include::compendium:page$Terminology/project-type__concept.adoc[tag=summary]

For more details, see xref:compendium:Terminology/project-type__concept.adoc[] in the Compendium.


== Standard Development
[tabs]
====
New Standard::
+
--
include::compendium:page$Terminology/project-type__standard.adoc[tag=new-summary]
--
Major Version Update::
+
--
include::compendium:page$Terminology/project-type__standard.adoc[tag=major-summary]
--
Minor Version Update::
+
--
include::compendium:page$Terminology/project-type__standard.adoc[tag=minor-summary]
--
Revision::
+
--
include::compendium:page$Terminology/project-type__standard.adoc[tag=revision-summary]
--
====

include::compendium:page$Terminology/project-type__standard.adoc[tag=summary]

For more details, see xref:compendium:Terminology/project-type__standard.adoc[] in the Compendium.

== Study
include::compendium:page$Terminology/project-type__study.adoc[tag=summary]

For more details, see xref:compendium:Terminology/project-type__study.adoc[] in the Compendium.



// == Implementation
// include::compendium:page$Terminology/project-type__implementation.adoc[tag=summary]

// For more details, see xref:compendium:Terminology/project-type__implementation.adoc[] in the Compendium.



