= Project phases
:description: An overview over the ASAM Project Phases.
:keywords: phase, concept

include::partial$_attributes.adoc[]


{project-phases-icon}

== Introduction

Besides xref:project_types.adoc[different types of projects], there are seven main project phases that ASAM defines.
Not all projects must necessarily pass through all these phases.
See the phase descriptions below for more details.

TIP: If you want to learn how to participate in a certain phase, check out the xref:getting-involved:main.adoc[] part for more information.

image::compendium:asam/project_lifecycle-v2.svg[alt=The ASAM Project Phases, title=The ASAM Project Phases]


[tabs]
====
Ideation::
+
--
include::getting-involved:partial$project_phases.adoc[tag=ideation]

If someone has an idea for a new standard, it triggers the ideation phase for a new project. +
During this phase, the idea is evaluated and fleshed out a bit until it is either discarded (e.g. it is not feasible or a duplicate of sorts) or accepted.
In case the idea is accepted, the project moves on to the xref:getting-involved:proposal_phase.adoc[].

Additional Information:: xref:getting-involved:ideation_phase.adoc[]
--
Proposal::
+
--
include::getting-involved:partial$project_phases.adoc[tag=proposal]


Whether a project idea was just accepted or an improvement or update on an existing standard was proposed, the project enters the Proposal Phase.
During this phase, a Proposal document is generated, detailing the project's targets, participants, the budget, timeline, and other project-related information.
The Project Type is also specified during this phase.
With this document, the ASAM TSC decides if the project may continue or not. +
If the go-ahead is given, the project continues on to the <<Development phase>>.

Additional Information:: xref:getting-involved:proposal_phase.adoc[]
--
Development::
+
--
include::getting-involved:partial$project_phases.adoc[tag=development]

**This is the main phase of each project.** +
During this phase, the project-type specific deliverables are developed by the project participants.
In the beginning, the project team organizes a workshop to specify their modus operandi and set up all technical aspects of the project.
This is followed by specifying, writing, and reviewing content internally until the document or documents are ready for a ASAM-internal or public review in the <<Review phase>>.

Additional Information:: xref:getting-involved:development_phase.adoc[]
--
Review::
+
--
include::getting-involved:partial$project_phases.adoc[tag=review]

Before they are officially released, the created deliverables are to be reviewed.
Depending on the project, these reviews may be available to ASAM members only, free for the public, or a mixture of both.
Any problems that are identified during any of these reviews are then analyzed and categorized.
Important fixes have to be made before the deliverables are released, whilst improvements beyond the initial scope or minute details may be put off for future iterations.

Additional Information:: xref:getting-involved:review_phase.adoc[]
--
Release::
+
--
include::getting-involved:partial$project_phases.adoc[tag=release]

After the deliverables have been developed and (optionally) successfully reviewed by the TSC, they are released to the public. +
The project has now concluded.
Developed and updated standards, however, will receive and process feedback afterwards in the <<Public phase>>.

Additional Information:: xref:getting-involved:release_phase.adoc[]
--
Public::
+
--
include::getting-involved:partial$project_phases.adoc[tag=public]

During this phase, the released standard is publicly available and officially supported.
There is no active development on the standard itself.
However, feedback from users may still be gathered in order to start a follow-up project down the line to improve the standard.
In this case, a new Project Proposal would be created and the process started anew. +
If, however, the standard at some point becomes obsolete or deprecated, it enters its final phase: the <<Retirement phase>>.
--
Retirement::
+
--
include::getting-involved:partial$project_phases.adoc[tag=retirement]

This phase is the final phase for every standard eventually.
The standard has become obsolete and is retired.
With this, it will no longer be supported and propagated by ASAM.
--
====

// == Ideation phase
// include::getting-involved:partial$project_phases.adoc[tag=ideation]

// If someone has an idea for a new standard, it triggers the ideation phase for a new project. +
// During this phase, the idea is evaluated and fleshed out a bit until it is either discarded (e.g. it is not feasible or a duplicate of sorts) or accepted.
// In case the idea is accepted, the project moves on to the xref:getting-involved:proposal_phase.adoc[].

// Additional Information:: xref:getting-involved:ideation_phase.adoc[]


// == Proposal phase
// include::getting-involved:partial$project_phases.adoc[tag=proposal]


// Whether a project idea was just accepted or an improvement or update on an existing standard was proposed, the project enters the Proposal Phase.
// During this phase, a Proposal document is generated, detailing the project's targets, participants, the budget, timeline, and other project-related information.
// The Project Type is also specified during this phase.
// With this document, the ASAM TSC decides if the project may continue or not. +
// If the go-ahead is given, the project continues on to the <<Development phase>>.

// Additional Information:: xref:getting-involved:proposal_phase.adoc[]

// == Development phase
// include::getting-involved:partial$project_phases.adoc[tag=development]

// **This is the main phase of each project.** +
// During this phase, the project-type specific deliverables are developed by the project participants.
// In the beginning, the project team organizes a workshop to specify their modus operandi and set up all technical aspects of the project.
// This is followed by specifying, writing, and reviewing content internally until the document or documents are ready for a ASAM-internal or public review in the <<Review phase>>.

// Additional Information:: xref:getting-involved:development_phase.adoc[]


// == Review phase
// include::getting-involved:partial$project_phases.adoc[tag=review]

// Before they are officially released, the created deliverables are to be reviewed.
// Depending on the project, these reviews may be available to ASAM members only, free for the public, or a mixture of both.
// Any problems that are identified during any of these reviews are then analyzed and categorized.
// Important fixes have to be made before the deliverables are released, whilst improvements beyond the initial scope or minute details may be put off for future iterations.

// Additional Information:: xref:getting-involved:review_phase.adoc[]

// == Release phase
// include::getting-involved:partial$project_phases.adoc[tag=release]

// After the deliverables have been developed and (optionally) successfully reviewed by the TSC, they are released to the public. +
// The project has now concluded.
// Developed and updated standards, however, will receive and process feedback afterwards in the <<Public phase>>.

// Additional Information:: xref:getting-involved:release_phase.adoc[]

// == Public phase
// include::getting-involved:partial$project_phases.adoc[tag=public]

// During this phase, the released standard is publicly available and officially supported.
// There is no active development on the standard itself.
// However, feedback from users may still be gathered in order to start a follow-up project down the line to improve the standard.
// In this case, a new Project Proposal would be created and the process started anew. +
// If, however, the standard at some point becomes obsolete or deprecated, it enters its final phase: the <<Retirement phase>>.


// == Retirement phase
// include::getting-involved:partial$project_phases.adoc[tag=retirement]

// This phase is the final phase for every standard eventually.
// The standard has become obsolete and is retired.
// With this, it will no longer be supported and propagated by ASAM.