= Roles Overview
:description: Links to the current contact page for ASAM Office members.
:keywords: roles, asam, concept

include::partial$_attributes.adoc[]
include::{abb}[]

{roles-icon}

include::role-specific:partial$roles.adoc[tag=summary]

== Overview

image::roles_overview.drawio.svg[title=Overview over the most relevant roles in ASAM projects.]

It is possible to have more than one role at the same time.
Some roles require you to "enroll in a project" first.
You can learn more about this process on the page xref:getting-involved:signing_up.adoc[].

== Role Descriptions
The following table contains a list of the most prominent roles at ASAM and a short description for each of them.

[cols = "1,3", frame=none, stripes=hover]
|===
2+s|[.underline]#External roles#
h|xref:role-specific:standard_user.adoc[(1) Standard User]
a|Someone who has access to and possible is an active user of any ASAM standard. +
Some standards require https://www.asam.net/about-asam/join-asam/[ASAM membership^] in order to access the documents, whilst other standards are available to anyone online. +
The role __Standard User__ is not directly involved in the creation of a standard.
However, a __Standard User__ may take over other (active) roles in a project by enrolling in it.

h|xref:role-specific:reviewer.adoc[(2) Reviewer]
a|An ASAM member outside the project that participates in the review of one or more documents. +
When a project's deliverable are reviewed, ASAM members that were not involved in the project directly can participate in the Review phase by becoming a __Reviewer__ and providing feedback.

2+s|[.underline]#Project roles#
h|xref:role-specific:wg-member.adoc[(3) Project Participant]
a|An ASAM member active in an ASAM project. +
Each project consists of many different __Project Participants__ that directly contribute to the project's development.
Most participants typically enroll during the xref:getting-involved:proposal_phase.adoc[], but it also possible to already participate during the xref:getting-involved:ideation_phase.adoc[]. +
Typically, __Project Participants__ work in one or more so-called Working Groups, each focussing on a specific aspect of the project.

h|xref:role-specific:project-lead.adoc[(4) Project Lead]
a|The __Project Participant__ responsible for the project and leading the general project activities. +
Every project needs one elected __Project Lead__ who takes responsibility for it.
The __Project Lead__ is elected at the beginning of the xref:getting-involved:development_phase.adoc[].
Any __Project Participant__ can send in their xref:getting-involved:proposal/submit_candidacy.adoc[candidacy] during the xref:getting-involved:proposal_phase.adoc[].

h|xref:role-specific:wg-lead.adoc[(5) Working Group Lead]
a|A __Project Participant__ leading the activities of a Working Group. +
Many projects divide up their activities into so-called Working Groups that focus on specific aspects of a project.
Each of these groups may be led by a __Working Group Lead__.

2+s|[.underline]#Supporting roles#
h|xref:role-specific:gtm.adoc[(6) Global Technology Manager (GTM)]
a|ASAM contact of the project. +
A __GTM__ is an ASAM employee focussed on coordinating project processes and the background work behind a project.


h|xref:role-specific:technical-writer.adoc[(7) Technical Writer]
a|Editor and writing support. +
A __Technical Writer__ supports the creation of documents.
They ensure ASAM's xref:compendium:writing_guidelines/editorial_guide.adoc[Editorial Guide] is applied and the document is formalized.

h|xref:role-specific:tsc.adoc[(8) Technical Steering Committee (TSC)]
a|Committee at ASAM reviewing a project's state. +
The TSC is responsible for approving or rejecting budgets, projects and proposals as well as releases of project results, such as standards or concept papers.

|===

== Further Information

For a complete overview over roles at ASAM, see xref:role-specific:main.adoc[].

// related::role[]