= Project roles & structure
:description: Defines all terms used when referencing an ASAM project.
:keywords: concept, project

include::partial$_attributes.adoc[]

== Project structure

Project:: ASAM activities are always organized in projects. A project at ASAM is a temporary endeavor undertaken to achieve a particular aim with a definite beginning and a definite end. ASAM standardization activities are always organized in projects. 
+
A project may be anything from a whitepaper, a study group to develop knowledge, a concept to begin defining concepts for a potential standard, or a standardization effort to develop new standards or improve on existing standards.

Project group:: The full group of all formally enrolled project participants. A formal organizational structure comprising project participants assigned to collectively achieve the objectives and deliverables of a project. It serves as the primary unit for project management and coordination.

[[project-member]]
Project member:: A company enrolled in a project via one or more project participants. A project member has one vote, irrespective of the number of it's project participants.

Project participant:: An individual, representing a project member, enrolled in a project with a defined commitment. Actively involved in a project's activities, tasks, or processes, contributing to the project's planning, execution, monitoring, and completion. Contributors may assume various roles and responsibilities, and their involvement can vary in scope and duration based on their contributions to the project. 

Subgroup:: A subgroup is a subset of the project group composed of voluntary project participants who collaborate on specific tasks, functions, or areas within the project. Subgroups are formed to enhance focus, efficiency, and specialization within the larger project group. Subgroups work collaboratively with other subgroups and the main project group to ensure that their contributions align with the overall project objectives.

CCB:: A subgroup of *experts from the project* taking on this *optional* and *additional role*.
The __Change Control Board (CCB)__ is responsible for internal alignment of topics, release management and approval/review of pull requests: 

* Issue and MR/PR review
* Classification of issues
* Assignment of issues to solution developer(s)
* Milestone monitoring and planning
* Ensure alignment of individual Subgroup topics
* Release management

+
Commitment to the CCB is for the duration of a project.
Average commitment entails 1-2 hour meetings every 2 weeks during active development and offline review of content.


Technical Steering Comittee (TSC):: 
The ASAM Technical Steering Committee is a group of elected members to which the ASAM Board of Directors has delegated various technical and strategic tasks.  
+
The Technical Steering Committee decides about and controls all technical projects at ASAM. The main task of the TSC is to ensure that the product portfolio of ASAM meets market needs and stays competitive.  
+
The TSC evaluates and votes on proposals for the development or enhancement of products, monitors the progress of ongoing projects, reviews and releases new or revised products. The TSC ensures that products do not overlap or contradict each other. See the https://www.asam.net/index.php?eID=dumpFile&t=f&f=249&token=46fe3fb6dfd4ce05d8fe40415b37babebdaafd25[TSC Guidelines] for further detail on this ASAM body.

== Project roles

[[asam_or]]
Office Responsible (OR):: The ASAM contact for a project. An __Office Responsible (OR)__ is an *ASAM employee* focussed on *coordinating project processes* and the *background work* behind a project.

Project Lead (PL):: The __Project Participant__ *responsible for the project* and leading the general project activities. +
*Every project needs one* elected __Project Lead__ who takes responsibility for it.
The __Project Lead__ is elected at the beginning of the Development Phase.
Any __Project Participant__ can send in their candidacy during the Proposal Phase.


Subgroup Lead (SGL):: An **active** __Project Participant__ *leading* the activities of a *subgroup*. +

Technical Writer (TW):: See Integrator.

[[integrator]]
Integrator:: A role prescribed by the xref:tour_guide:page$contribution.adoc[ASAM contribution workflow]. This role is specified by each project prior to starting development, in most cases this should be a project kickoff. The Integrator is responsible for integrating the developed solution into the standard. Their task is to make sure the writing style is kept consistent and the ASAM editorial rules are met.
+
The Integrator may be a service provider tasked with documentation efforts in the project. Alternatively, the Integrator may be the Office Responsible or a project participant. The integrator shall be clearly named in a project repository readme.

[[workflow-manager]]
Workflow manager:: A role prescribed by the xref:tour_guide:page$contribution.adoc[ASAM contribution workflow]. Orchestrates and manages the entire workflow, the process through which contributions are reviewed, approved, merged, and integrated into a project. Typically, the Workflow Manager is experienced with using remote repositories. This role is assigned to a specific project participant or subgroup by a project prior to starting development, in most cases this should be a project kickoff.
This may be any one of:

* Project Lead
* Office Responsible
* Subgroup Lead
* Change Control Board (CCB)
* Project participant


Solution responsible:: A role prescribed by the xref:tour_guide:page$contribution.adoc[ASAM contribution workflow]. An individual to whom a specific issue has been assigned that is responsible for developing or ensuring the development and finalisation of a solution addressing it (InProgress state).

Solution team:: A group of project participants responsible for contributing to the development of a solution, also includes the solution responsible. May be a project subgroup or a group specific to the issue.

