
//tag::summary[]
Within projects at ASAM, participant have one or more roles.
Each of these roles has their own set of requirements, mandatory and/or optional tool, guidelines and how-tos, some of them shared between multiple roles.
//end::summary[]

//tag::list_of_roles[]

// TIP: Click on a role's label to navigate directly to the role's summary page.

=== Outside roles
[cols = ">1,^5,20", frame=none, stripes=hover]
|===
// 3+<s|[.underline]#Outside roles#
|(1)
|image:compendium:Concepts/roles_overview-standard_user.svg[]
a|Someone who has *access to* and possibly is an *active user of any ASAM standard*. +
Some standards require https://www.asam.net/about-asam/join-asam/[ASAM membership^] in order to access the documents, whilst other standards are available to anyone online. +
The role __Standard User__ is *not directly involved* in the creation of a standard.
However, a __Standard User__ may take over other (active) roles in a project by enrolling in it. +
**Note that project participation also requires ASAM membership!**

|(2)
|image:compendium:Concepts/roles_overview-reviewer.svg[]
a|A __Standard User__ that participates in the *review of one or more documents*. 
They are considered non-enrolled Reviewers. +
When a project's deliverables are reviewed, ASAM members who were not involved in the project directly can participate in the Review phase by becoming a __Reviewer__ and providing feedback.
In case the project has a public review, ASAM membership is not required.

ASAM members can also enroll specifically as Reviewers for projects. 
In this case, they become a participant that has committed a small amount of resources to support the project team with review focused activities. 
This may include review of merge requests, proposals and/or review of documents. +
The following points are related to such enrolled reviewers: 

* Company being represented must be an ASAM Member
* Has committed resources for review
* Has access to the Sharepoint
* Has reporter access to the project Gitlab
|===

=== Project roles
[cols = ">1,^5,20", frame=none, stripes=hover]
|===
// 3+<s|[.underline]#Project roles#
|(3)
|image:compendium:Concepts/roles_overview-project_participant.svg[]
a|An *ASAM member participating in an ASAM project*. +
Each project consists of *multiple* __Project Participants__. +
There are two different types of project participants: **contributors** and **spectators**.

Contributor:: 
(renamed, renamed, previously used member / active member)
A participant in an ASAM project that has committed resources to contributing to the project. 
They typically work in one or more subgroups, each focussing on a specific aspect of the project. +
* The company being represented must be an ASAM Member
* Has committed resources
* Has access to the project Sharepoint
* Has developer access to the project GitLab
* Each company with at least one contributor has one vote

Spectator::
Passive participant or observer in an ASAM project that is part of a company **with at least one contributor** in the project. +
* The company being represented must be an ASAM Member
* Has access to the project Sharepoint
* Has reporter access to the project Gitlab


|(4)
|image:compendium:Concepts/roles_overview-project_lead.svg[]
a|The __Project Participant__ *responsible for the project* and leading the general project activities. +
*Every project needs one* elected __Project Lead__ who takes responsibility for it.
The __Project Lead__ is elected at the beginning of the Development Phase.
Any __Project Participant__ can send in their candidacy during the Proposal Phase.

|(5)
|image:compendium:Concepts/roles_overview-wg_lead.svg[]
a|An **active** __Project Participant__ *leading* the activities of a *subgroup*. +
Many projects divide up their activities into so-called subgroups which focus on specific aspects of a project.
Each of these groups may be led by a __Subgroup Lead__.


|(6)
|
a|A subgroup of experts in the project responsible for internal alignment of topics, release management & approval/review of pull requests. This is an optional additional role in a project. +
* Issue and MR/PR review
* Classification of issues
* Assignment of issues to solution developer(s)
* Milestone monitoring and planning
* Ensure alignment of individual Subgroup topics
* Release management
Commitment to the CCB is for the duration of a project.
Average commitment entails 1-2 hour meetings every 2 weeks during active development and offline review of content.

|===

=== Other roles
[cols = ">1,^5,20", frame=none, stripes=hover]
|===
// 3+<s|[.underline]#Supporting roles#
|(7)
|image:compendium:Concepts/roles_overview-or.svg[]
a|ASAM contact of the project. +
An __Office Responsible (OR)__ is an *ASAM employee* focussed on *coordinating project processes* and the *background work* behind a project.

|(8)
|image:compendium:Concepts/roles_overview-tw.svg[]
a|Editor and writing support. +
A __Technical Writer__ *supports* the *creation of documents*.
They ensure **ASAM's Editorial Guide** is applied and the document is formalized.

|(9)
|image:compendium:Concepts/roles_overview-tsc.svg[]
a|*Committee at ASAM reviewing a project's state*. +
The TSC is responsible for *approving or rejecting* budgets, projects and proposals as well as releases of project results, such as standards or concept papers.

|===


//end::list_of_roles[]