= Working Online
:description: Contains an overview over when and how working without any additional software installation is possible.
:keywords: online,recommended

include::partial$_attributes.adoc[]
include::{abb}[]

{mandatory}

== Overview

{remote-xref}[Remote Repositories] provide an integrated working environment and text editor with which users can directly create and edit files without having to install xref:git.adoc[] or an editor like xref:vscode.adoc[]. +
The choice of remote repository depends on the project.
ASAM recommends looking up specific questions on these platforms and their features in general on their respective online documentation.
Topics related to ASAM rules in projects (e.g. for using issue templates) can be found in the {remote-xref}[Remote Repositories Info Page].

However, note that you will still need to configure an account.
Also note that some tasks may be easier or more convenient to be done with local setups.

== Minimum Required Setup
Whether you prefer to work online or with locally installed software, you must do a minimum setup before you can participate in and contribute to any project. +
To do so, go through the setup description for each of the platforms and tools listed in the table below.


include::tooling:partial$list-of-tools.adoc[tag=mandatory]