= Ideation Workshop
:description: Describes how an idea can be developed at ASAM.
:keywords: ideation, workshop

include::partial$_attributes.adoc[]


[cols="1,5", grid = rows]
|===
h|Responsible
|{role-gtm}
h|Involved
| {role-standard-user}, {role-idea-giver}

h| Step
| image:compendium:asam/ideation_phase-ideation_workshop.svg[]

h| TL;DR
a| * GTM prepares the workshop and informs interested parties
* Idea and input is presented at workshop, parties flesh out the idea
* Next steps are decided and interested parties are consolidated
|===


== Context
When enough interest is raised (subject to suitable market relevance) and the idea would be to create a new standard, ASAM will host an <<The Ideation Workshop,Ideation Workshop>> to further develop the topic.
If required, an Ideation project is set up that will meet regularly.

WARNING: The existence of Ideation projects is still open for discussion.


== Goals
The goal of an Ideation Workshop is to investigate and develope the proposed idea enough to be able to make a decision on whether the idea is ready for a Project Proposal.


== Results
* The idea has been presented and discussed at the Ideation Workshop
* A decision on whether to proceed to the Proposal phase has been reached
* (OPTIONAL) Participants have signed up to participate in the Proposal phase (see xref:ideation/raising_interest.adoc[])
* The protocol of the workshop is communicated


== How
. The GTM prepares the workshop using the xref:compendium:Templates/ideation_workshop_gameplan.adoc[]
. The GTM informs people who have already signed up to the ideation workshop
* Optionally, the GTM broadly informs all ASAM members if this approach seems necessary
. The Workshop happens, following the outline of the <<Typical workshop agenda>> shown below
* Ideally, interested parties already sign up for the Proposal Phase (see xref:ideation/raising_interest.adoc[])
. The GTM creates a protocol of the event and sends it to all people who had signed up


== Typical workshop agenda
include::compendium:Templates/ideation_workshop_gameplan.adoc[tag=agenda_example]

