name: asam-project-guide-content-udpate

on:
  push: # on push
    branches:
    - main
    - 'restructuring_**'
  workflow_dispatch: # manual trigger

jobs:
  notify:
    name: Notify the generator about the update
    runs-on: ubuntu-20.04
   
    steps:
    - name: Repository Dispatch
      # You may pin to the exact commit or the version.
      # uses: peter-evans/repository-dispatch@ce5485de42c9b2622d2ed064be479e8ed65e76f4
      uses: peter-evans/repository-dispatch@v1.1.3
      with:
        # A repo scoped GitHub Personal Access Token
        token: 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
        # The full name of the repository to send the dispatch.
        repository: asam-ev/asam-project-guide
        # A custom webhook event name.
        event-type: content-update
